-- 기수 성적 카테고리 테이블  	-- 
CREATE TABLE STU_CAT_TB(
	CAT_SEQ 				INT(10) PRIMARY KEY,							-- 카테고리	번호 	--
    CRC_ID 					VARCHAR(12),									-- 과정		ID 		--
    GISU_ID 				VARCHAR(12),									-- 기수		ID		--
    CAT_NM 					VARCHAR(50) NOT NULL,							-- 카테고리	이름		--					
    CAT_PERCENT				DECIMAL(10,2) UNSIGNED NOT NULL,				-- 카테고리	배율 	--
    BIG_CAT_SEQ				INT(10) DEFAULT 0,								-- 대분류 카테고리 번호 	--
    MID_CAT_SEQ				INT(10) DEFAULT 0,								-- 중분류 카테고리 번호 	--
    FOREIGN KEY(CRC_ID) REFERENCES CB_COURSE(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(GISU_ID) REFERENCES CB_CARDINAL(ID) ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';
    
-- 시험 테이블 				-- 
CREATE TABLE STU_TEST_TB(
	TEST_SEQ 				INT(10) PRIMARY KEY,							-- 시험		번호		--
    CAT_SEQ 				INT(10)			NOT NULL,						-- 카테고리	번호		--
    TEST_NM 				VARCHAR(50)	 	NOT NULL,						-- 시험		이름 	--
    TOTAL_SCORE 			INT(3) UNSIGNED DEFAULT 100,					-- 총합 		점수 	--
    TEST_CONTENT 			VARCHAR(2000) 	NOT NULL, 						-- 시험		내용		--
    RETEST_TIME 			INT(3) UNSIGNED DEFAULT 0, 						-- 재응시 	횟수 	--
    TEST_YN					VARCHAR(10) DEFAULT 'FALSE',					-- 시험응시 	여부		--
    TEST_START_DATE 		DATETIME DEFAULT CURRENT_TIMESTAMP,				-- 시험		시작날짜	--
    TEST_END_DATE 			DATETIME DEFAULT CURRENT_TIMESTAMP,				-- 시험		종료날짜 	--
    TEST_REGDATE 			DATETIME DEFAULT CURRENT_TIMESTAMP,				-- 시험		등록날짜	--
    TEST_UPDATE 			DATETIME DEFAULT CURRENT_TIMESTAMP,				-- 시험		수정날짜	--
    FOREIGN KEY(CAT_SEQ) REFERENCES STU_CAT_TB(CAT_SEQ) ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';

-- 성적 테이블 			 	--
CREATE TABLE STU_TEST_SCORE_TB(
	SCORE_SEQ 				INT(10) NOT NULL,								-- 성적 		번호 	--
    TEST_SEQ				INT(10) NOT NULL,								-- 시험		번호 	--
    USER_ID					VARCHAR(50) NOT NULL,							-- 학생		ID		--
    PLUS_SCORE				INT(10) UNSIGNED DEFAULT 0,						-- 가산점		번호		--
    SCORE					DECIMAL(10,2) UNSIGNED NOT NULL,				-- 점수				--		(소수점2자리까지)
    RETEST					INT(3) UNSIGNED DEFAULT 0,						-- 재응시		횟수 	--
    CONTENT					VARCHAR(255) DEFAULT '없음',						-- 비고 				--
    SCORE_REGDATE			DATETIME DEFAULT CURRENT_TIMESTAMP,				-- 성적		등록날짜 	--
    SCORE_UPDATE			DATETIME DEFAULT CURRENT_TIMESTAMP,				-- 성적		수정날짜 	--
    PRIMARY KEY(SCORE_SEQ),
    FOREIGN KEY(USER_ID) 		REFERENCES com_user_tb(USER_ID)						ON DELETE CASCADE,
    FOREIGN KEY(TEST_SEQ) 		REFERENCES STU_TEST_TB(TEST_SEQ)					ON DELETE CASCADE)
COLLATE='utf8_general_ci';

-- 반 관리 테이블 				--
CREATE TABLE STU_CLASS_INFO_TB(
	CLASS_SEQ				INT(10) NOT NULL,								-- 반 		번호 	--
	CLASS_UPPER_SEQ			INT(10) DEFAULT 0,								-- 상위 반	번호 	--
    CLASS_NAME				VARCHAR(50) NOT NULL,							-- 반		정보 	--
    CLASS_UPPER_NAME		VARCHAR(50) DEFAULT '',							-- 반		정보 	--
    CRC_ID					VARCHAR(12) NOT NULL,							-- 과정		번호		--
    GISU_ID					VARCHAR(12) NOT NULL,							-- 기수 		번호		--
    PRIMARY KEY(CLASS_SEQ),
    FOREIGN KEY(CRC_ID) 			REFERENCES CB_COURSE(ID) 		ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(GISU_ID) 			REFERENCES CB_CARDINAL(ID) 		ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';

-- 학생 반 정보 테이블 			--
CREATE TABLE STU_CLASS_TB(
    USER_ID					VARCHAR(50) NOT NULL,							-- 유저 		ID		--
    CLASS_SEQ				INT(10) NOT NULL,								-- 반 		정보 	--
    FOREIGN KEY(USER_ID) 	REFERENCES COM_USER_TB(USER_ID)	ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(CLASS_SEQ) 	REFERENCES STU_CLASS_INFO_TB(CLASS_SEQ)	ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';
    

-- 상담 신청 테이블 			--
CREATE TABLE STU_COUNSEL_TB(
	COUNSEL_SEQ 			INT(15) NOT NULL,
    USER_ID					VARCHAR(50) NOT NULL,
    COUNSEL_TYPE			VARCHAR(32) NOT NULL,
	COUNSEL_TITLE			VARCHAR(255) NOT NULL,
    COUNSEL_CONTENT			VARCHAR(10000) NOT NULL,
    COUNSEL_TEACHER			VARCHAR(50) NOT NULL,
    COUNSEL_REGDATE			DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(COUNSEL_SEQ),
    FOREIGN KEY(USER_ID) 			REFERENCES COM_USER_TB(USER_ID)	ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(COUNSEL_TEACHER) 	REFERENCES COM_USER_TB(USER_ID)	ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';


-- 설문지 세부 사항(관리) 테이블 	--
CREATE TABLE STU_SURVEY_INFO_TB(
	SURVEY_SEQ						INT(15) NOT NULL,
    CRC_ID							VARCHAR(12) NOT NULL,
    GISU_ID							VARCHAR(12) NOT NULL,
    SURVEY_TITLE					VARCHAR(255) NOT NULL,
    SURVEY_CONTENT					VARCHAR(10000) NOT NULL,
    SURVEY_START_DATE				DATETIME NOT NULL,
    SURVEY_END_DATE					DATETIME NOT NULL,
    SURVEY_REGDATE					DATETIME DEFAULT CURRENT_TIMESTAMP,
    SURVEY_UPDATE					DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(SURVEY_SEQ),
    FOREIGN KEY(CRC_ID) 			REFERENCES CB_COURSE(ID) 		ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(GISU_ID) 			REFERENCES CB_CARDINAL(ID) 		ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';

 -- 설문 유형 테이블 			--
CREATE TABLE STU_SURVEY_TYPE_INFO_TB(
	SURVEY_TYPE_SEQ					INT(3) NOT NULL,
    SURVEY_TYPE_NAME				VARCHAR(100) NOT NULL,
    PRIMARY KEY(SURVEY_TYPE_SEQ) )
COLLATE='utf8_general_ci';

INSERT INTO STU_SURVEY_TYPE_INFO_TB values (1,'객관식(다중 선택)');
INSERT INTO STU_SURVEY_TYPE_INFO_TB values (2,'객관식(단일 선택)');
INSERT INTO STU_SURVEY_TYPE_INFO_TB values (3,'주관식(단답형)');
INSERT INTO STU_SURVEY_TYPE_INFO_TB values (4,'주관식(장문형)');   

 -- 설문지 질문 테이블 			--
CREATE TABLE STU_SURVEY_QUESTION_TB(
	SURVEY_QUESTION_SEQ				INT(15) NOT NULL,
    SURVEY_SEQ						INT(15) NOT NULL,
    SURVEY_TYPE_SEQ					INT(3) NOT NULL,
    SURVEY_NUMBER					INT(3) NOT NULL,
    SURVEY_QUESTION					VARCHAR(255) NOT NULL,
    SURVEY_ANSWER_SAMPLE			VARCHAR(1023) DEFAULT '',
    PRIMARY KEY(SURVEY_QUESTION_SEQ),
    FOREIGN KEY(SURVEY_SEQ) 			REFERENCES STU_SURVEY_INFO_TB(SURVEY_SEQ) 					ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(SURVEY_TYPE_SEQ) 		REFERENCES STU_SURVEY_TYPE_INFO_TB(SURVEY_TYPE_SEQ) 		ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';
    
  -- 설문지 답변 테이블 			--  
CREATE TABLE STU_SURVEY_ANSWER_TB(
	SURVEY_ANSWER_SEQ					INT(15) NOT NULL,
    SURVEY_QUESTION_SEQ					INT(15) NOT NULL,
    USER_ID								VARCHAR(50) NOT NULL,
    SURVEY_ANSWER						VARCHAR(1023) DEFAULT '',
    SURVEY_ANSWER_CHOICE				INT(3) DEFAULT 0,
    SURVEY_ANSWER_HIDE					BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(SURVEY_ANSWER_SEQ),
    FOREIGN KEY(SURVEY_QUESTION_SEQ) 	REFERENCES STU_SURVEY_QUESTION_TB(SURVEY_QUESTION_SEQ) 		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(USER_ID) 				REFERENCES COM_USER_TB(USER_ID)								ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';


	-- 설문 응답 완료 명단 테이블	--
CREATE TABLE STU_SURVEY_COMPLETE_TB(
	SURVEY_COMPLETE_SEQ					INT(15) NOT NULL,
	SURVEY_SEQ							INT(15) NOT NULL,
    USER_ID 							VARCHAR(50) NOT NULL,
    PRIMARY KEY(SURVEY_COMPLETE_SEQ),
	FOREIGN KEY(SURVEY_SEQ) 			REFERENCES STU_SURVEY_INFO_TB(SURVEY_SEQ) 		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(USER_ID) 				REFERENCES COM_USER_TB(USER_ID)					ON UPDATE CASCADE ON DELETE CASCADE)
COLLATE='utf8_general_ci';

