CREATE TABLE CB_ALLIANCE_APP (
	ID INT(12)		NOT NULL			AUTO_INCREMENT			COMMENT '제휴문의 마스터 ID',
	USER_ID			VARCHAR(100)		NULL DEFAULT 'NULL' 	COMMENT '지원 유저',
	NAME			VARCHAR(100)		NOT NULL				COMMENT '성명',
	COMPANY_NAME	VARCHAR(100)		NOT NULL				COMMENT '회사명',
	PHONE			VARCHAR(50)			NULL DEFAULT NULL		COMMENT '연락처',
	EMAIL			VARCHAR(100)		NULL DEFAULT NULL		COMMENT '이메일',
	ALLIANCE_TYPE 	VARCHAR(12)			NULL DEFAULT NULL		COMMENT '제휴구분(AT001:연수제휴, AT002:콘텐츠제휴, AT003:사업제휴, AT004:마케팅제휴, AT005:기타제휴)',
	COMMENT			MEDIUMTEXT			NULL DEFAULT NULL		COMMENT '내용',
	USE_YN			CHAR(1)				NULL DEFAULT 'Y'		COMMENT '사용여부(Y : 사용, N : 미사용)',
	REG_DATE VARCHAR(14)				NULL DEFAULT NULL		COMMENT '등록일자',
	PRIMARY KEY (ID)
)
COMMENT='제휴문의 테이블';
