-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_ATT_LEC_HISTORY (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT '수강 이력 ID',
	LEARN_APP_ID		INT(12)			NOT NULL					COMMENT '수강신청ID',
	USER_ID				VARCHAR(100)	NOT NULL					COMMENT '수강자ID',
	CARDINAL_ID			VARCHAR(12)		NOT NULL					COMMENT '기수ID',
	COURSE_ID			VARCHAR(12)		NOT NULL					COMMENT '과정ID',
	CHAPTER				INT(12)			NOT NULL					COMMENT '챕터ID',
	CHASI				INT(3)			DEFAULT 1					COMMENT '차시(순서 1차시~30차시)',
	START_DATE			VARCHAR(14)									COMMENT '시작일시',
	END_DATE			VARCHAR(14)									COMMENT '종료일시'
) COMMENT='수강 이력 관리 테이블';