-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE `CB_BANNER` (
	`ID` INT(12) NOT NULL AUTO_INCREMENT COMMENT '배너 ID(SEQ로 ID저장)',
	`POSITION` CHAR(1) NULL DEFAULT NULL COMMENT '위치 (1 : 메인탑, 2 : 메인우측)',	
	`TITLE` VARCHAR(255) NULL DEFAULT NULL COMMENT '링크(배너)명',
	`URL` VARCHAR(500) NULL DEFAULT '1' COMMENT '링크',
	`TARGET` VARCHAR(20) NULL DEFAULT '1' COMMENT '링크 열림 유형',
	`ATTACH1_FILE` VARCHAR(20) NULL DEFAULT NULL COMMENT '첨부 #1 파일',Z
	`ATTACH2_FILE` VARCHAR(20) NULL DEFAULT NULL COMMENT '첨부 #2 파일',
	`USER_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '작성자 USER ID',	
	`USE_YN` CHAR(1) NULL DEFAULT 'Y' COMMENT '사용여부(Y : 사용, N : 미사용)',
	`REG_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자 ID',
	`REG_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`UPD_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자 ID',
	`UPD_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`ID`)
)
COMMENT='배너 관리 테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
