-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_BOARD_COMMENT (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT '댓글 마스터 ID(SEQ로 ID저장)',
	BOARD_ID			INT(12)			NOT NULL					COMMENT '게시글 ID',
	USER_ID				VARCHAR(100)								COMMENT '작성자 USER ID(사용자가 답글 남긴 경우)',
	COMMENT				VARCHAR(500)								COMMENT '댓글 내용'
) COMMENT='BOARD COMMENT TABLE';