-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_BOARD (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT '게시글 마스터 ID(SEQ로 ID저장)',
	LANG				CHAR(2)			DEFAULT 'ko'	NOT NULL	COMMENT '다국어 코드(ko:한국어, en:영어, zh:중국어, ja:일본어)',
	BOARD_TYPE			CHAR(1)			DEFAULT '1'					COMMENT '게시글 타입(1:공지사항, 2:자료실, 3:FAQ, 4:1:1상담, 5:연수후기, 6:질의응답)',
	NOTICE_TYPE			CHAR(1)			DEFAULT '1'					COMMENT '공지구분(1:모집, 2:환영, 3:신설, 4:필독, 5:일반, 6:평가, 7:공문)',
	FAQ_CODE			VARCHAR(12)									COMMENT 'FAQ인 경우 분류코드',
	CARDINAL_ID			VARCHAR(12)									COMMENT '기수ID',
	COURSE_ID			VARCHAR(12)									COMMENT '과정ID',
	TEACHER_ID			VARCHAR(100)								COMMENT '강사ID',
	USER_ID				VARCHAR(100)								COMMENT '작성자 USER ID',
	ATTACH1_FILE		VARCHAR(20)									COMMENT '첨부 #1 파일',
	ATTACH2_FILE		VARCHAR(20)									COMMENT '첨부 #2 파일',
	ICON				CHAR(1)										COMMENT '아이콘(1:New, 2:Hot)',
	TOP_YN				CHAR(1)			DEFAULT 'N'					COMMENT '탑 고정 YN',
	SECRET_YN			CHAR(1)			DEFAULT 'N'					COMMENT '비밀글 여부(Y/N)',
	TITLE				VARCHAR(255)								COMMENT '게시물 제목',
	COMMENT				MEDIUMTEXT									COMMENT '게시물 내용',
	HITS				INT(8)			DEFAULT 0					COMMENT '조회수',
	RECOMMEND			INT(8)			DEFAULT 0					COMMENT '추천수',
	NONRECOMMEND		INT(8)			DEFAULT 0					COMMENT '비추천수',
	SHARE				INT(8)			DEFAULT 0					COMMENT '공유횟수',
	ORDER_NUM			INT(3)			DEFAULT 1					COMMENT 'DISPLAY순서(게시판 기준으로 ORDER)',
	USE_YN				CHAR(1)			DEFAULT 'Y'					COMMENT '사용여부(Y : 사용, N : 미사용)',
	REG_USER        	VARCHAR(100)                             	COMMENT '등록자 ID',
	REG_DATE			VARCHAR(14)									COMMENT '등록일자',
  	UPD_USER        	VARCHAR(100)                             	COMMENT '수정자 ID',
	UPD_DATE		  	VARCHAR(14)									COMMENT '수정일자'
) COMMENT='BOARD MASTER TABLE';