-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_COURSE (
	SEQ					INT(12)			AUTO_INCREMENT	UNIQUE		COMMENT '연수과정 마스터 SEQ',
	ID					VARCHAR(12)		PRIMARY KEY					COMMENT '연수과정 ID',
	COURSE_CODE			CHAR(12)									COMMENT '과정타입(c001:교직기본소양, c002:교수학습지도, c003:학급경영및생활지도, c004:일반교양)',
	COM_ID				VARCHAR(100)								COMMENT '업체 ID(관리자처럼 관리)',
	COM_CAL				VARCHAR(5)									COMMENT '업체 정산지급(%)',
	TEACH_ID			VARCHAR(100)								COMMENT '강사 ID(관리자처럼 관리)',
	TEACH_CAL			VARCHAR(5)									COMMENT '강사 정산지급(%)',
	TUTOR_CAL			VARCHAR(5)									COMMENT '튜터 정산지급(%)',
	TB_CODE				VARCHAR(12)									COMMENT '교재업체 코드',
	NAME				VARCHAR(100)	NOT NULL					COMMENT '과정명',
	SHORT_NAME			VARCHAR(50)		NOT NULL					COMMENT '과정줄임명',
	MAIN_YN				CHAR(1)			DEFAULT 'N'					COMMENT '메인표시여부',
	MAIN_DISPLAY		CHAR(1)										COMMENT '메인표시(1:창비추천, 2:초등추천, 3:중등추천)',
	ICON_DISPLAYS		VARCHAR(20)									COMMENT '아이콘표시 다중표시(1:NEW, 2:BEST, 3:인기, 4:업그레이드, 5:우수) - 다중선택',
	COMPLETE_TIME		INT(3)			DEFAULT 0					COMMENT '이수시간',
	LEARN_TYPES			VARCHAR(20)									COMMENT '연수타입(J : 직무, S : 자율, M : 집합) - 다중 선택',
	TARGET_TYPES		VARCHAR(20)									COMMENT '대상타입(1:유아, 2:초등, 3:중등, 4:전문직) - 다중 선택',
	CREDIT				INT(1)			DEFAULT 1					COMMENT '학점(1~4)',
	LEARN_TARGET		VARCHAR(200)								COMMENT '연수대상',
	PRICE				INT(10)			DEFAULT 0					COMMENT '수강금액',
	PROG_CHECK			INT(2)			DEFAULT 0					COMMENT '진도체크(차시당 분)',
	OPEN_DATE			VARCHAR(10)									COMMENT '과정오픈일',
	APP_DATE			VARCHAR(10)									COMMENT '심사신청일',
	RECRUIT				INT(3)			DEFAULT 0					COMMENT '모집인원',
	EXAM_PERIOD			INT(1)			DEFAULT 1					COMMENT '시험교시(4학점 출석시험인 경우 사용)',
	MAIN_TB_ID			INT(12)										COMMENT '메인교재 ID',
	SUB_TB_ID			INT(12)										COMMENT '교구ID',
	MAIN_PRICE			INT(10)			DEFAULT 0					COMMENT '주교재 가격',
	SUB_PRICE			INT(10)			DEFAULT 0					COMMENT '교구 가격',
	LINK_SERVER			INT(1)			DEFAULT 1					COMMENT '창비링크서버(1~2)',
	GROUP_YN			CHAR(1)			DEFAULT 'N'					COMMENT '단체연수신청여부',
	MOBILE_YN			CHAR(1)			DEFAULT 'N'					COMMENT '모바일 서비스 여부',
	INDEX_URL			VARCHAR(500)								COMMENT '인덱스',
	TASTING_URL			VARCHAR(500)								COMMENT '맛보기',
	SAMPLE_URL			VARCHAR(500)								COMMENT '교재샘플',
	WIDTH				VARCHAR(4)									COMMENT '넓이',
	HEIGHT				VARCHAR(4)									COMMENT '높이',
	SELP_PERIOD			INT(3)			DEFAULT 0					COMMENT '자율 연수인 경우 연수기간(인증일로부터 00일)',
	MAIN_IMG_FILE		VARCHAR(20)									COMMENT '대표 이미지 파일',
	DUP_DIS_YN			CHAR(1)			DEFAULT 'N'					COMMENT '중복할인 허용 여부',
	ACCEPT_YN			CHAR(1)			DEFAULT 'N'					COMMENT '접수상태',
	PURPOSE				TEXT										COMMENT '과정목표',
	SUMMARY				TEXT										COMMENT '과정개요',
	INSTRUCTOR			TEXT										COMMENT '강사진 안내',
	NOTE				TEXT										COMMENT '유의사항',
	MOBILE_SUMMARY		TEXT										COMMENT '모바일 과정개요',
	DEVELOPER			VARCHAR(50)									COMMENT '과정개발자',
	RES_TEL				VARCHAR(50)									COMMENT '담당전화',
	COM_NAME			VARCHAR(50)									COMMENT '제작업체명',
	COM_TEL				VARCHAR(50)									COMMENT '업체전화',
	PRODUCE_DATE		VARCHAR(10)									COMMENT '제작일',
	STORAGE_LOC			VARCHAR(100)								COMMENT '보관위치',
	HISTORY				TEXT										COMMENT '제작히스토리',
	REMARKS				TEXT										COMMENT '특이사항 및 비고',
	ORDER_NUM			INT(3)			DEFAULT 1					COMMENT '순서(필요없음)',
	SELL_ORDER			INT(10)			DEFAULT 1					COMMENT '판매순위',
	HITS_ORDER			INT(10)			DEFAULT 1					COMMENT '인기순위',
	USE_YN				CHAR(1)			DEFAULT 'Y'					COMMENT '사용여부(Y : 사용, N : 미사용)',
	REG_USER        	VARCHAR(100)                             	COMMENT '등록자 ID',
	REG_DATE			VARCHAR(14)									COMMENT '등록일자',
  	UPD_USER        	VARCHAR(100)                             	COMMENT '수정자 ID',
	UPD_DATE		  	VARCHAR(14)									COMMENT '수정일자'
) COMMENT='연수과정 관리 테이블';