-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE `CB_EVENT` (
	`ID` INT(12) NOT NULL AUTO_INCREMENT COMMENT '이벤트 ID(SEQ로 ID저장)',
	`TITLE` VARCHAR(255) NULL DEFAULT NULL COMMENT '이벤트 제목',
	`COMMENT` MEDIUMTEXT NULL DEFAULT NULL COMMENT '이벤트 내용',
	`USER_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '작성자 USER ID',
	`START_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '이벤트 시작 기간',
	`END_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '이벤트 종료 기간',
	`ATTACH1_FILE` VARCHAR(20) NULL DEFAULT NULL COMMENT '첨부 #1 파일 (인덱스 배너)',
	`ATTACH2_FILE` VARCHAR(20) NULL DEFAULT NULL COMMENT '첨부 #2 파일',
	`APPROVAL_STATUS` CHAR(1) NULL DEFAULT '1' COMMENT '승인상태(1 : 노출보류, 2 : 서비스(게시))',
	`ORDER_NUM` INT(3) NULL DEFAULT 1 COMMENT '표출우선순위',
	`USE_YN` CHAR(1) NULL DEFAULT 'Y' COMMENT '사용여부(Y : 사용, N : 미사용)',
	`REG_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자 ID',
	`REG_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`UPD_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자 ID',
	`UPD_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`ID`)
)
COMMENT='이벤트 관리 테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
