CREATE TABLE CB_EXAM_TAKE_HISTORY (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT '시험 응시 ID',
	LEARN_APP_ID		INT(12)			NOT NULL					COMMENT '수강신청ID',
	QUIZ_ID				VARCHAR(20)		NOT NULL					COMMENT '시험 ID',
	USER_ID				VARCHAR(20)		NOT NULL					COMMENT '평가대상 ID',
	REG_USER        	VARCHAR(100)                             	COMMENT '등록자 ID',
	REG_DATE			DATETIME		DEFAULT CURRENT_TIMESTAMP()	COMMENT '등록일자'
) COMMENT='시험 응시 내역 테이블';


CREATE INDEX EXAM_TAKE_HISTORY_IDX01 ON CB_EXAM_TAKE_HISTORY
(LEARN_APP_ID, QUIZ_ID);