-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_GROUP_CN (
	SEQ					INT(12)			AUTO_INCREMENT	UNIQUE		COMMENT '기수 연동 SEQ',
	GROUP_ID			VARCHAR(12)									COMMENT '단체연수관리 ID',
	CARDINAL_ID			VARCHAR(12)									COMMENT '기수 ID',
	LIMIT_NUM			INT(3)			DEFAULT 0					COMMENT '신청제한인원',
	PRIMARY KEY(GROUP_ID, CARDINAL_ID)
) COMMENT='단체연수 기수 연동 TABLE';