
CREATE TABLE CB_HIT_KEYWORD
(
	SEQ int(12) NOT NULL AUTO_INCREMENT COMMENT '키워드SEQ',
	KEYWORD varchar(50) NOT NULL COMMENT '키워드',
	ORDER_NUM int(3) DEFAULT 1 NOT NULL COMMENT '순서',
	USE_YN varchar(1) DEFAULT 'Y' NOT NULL COMMENT '사용여부',
	REG_USER varchar(100) COMMENT '등록자 ID',
	REG_DATE datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	UPD_USER varchar(100) COMMENT '수정자 ID',
	UPD_DATE datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
	PRIMARY KEY (SEQ)
) COMMENT = '인기검색어';
