-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE `CB_INFO` (
	`ID` INT(12) NOT NULL AUTO_INCREMENT COMMENT '안내 ID(SEQ로 ID저장)',
	`THEMA_TYPE` INT(2) NULL DEFAULT NULL COMMENT '테마타입 (1 : 회원약관, 2 : 개인정보보호정책, 3 : 소개, 4 : 연혁, 5 : 조직도, 6 : 찾아오시는길, 7 : 규정, 8 : 교육부 인가서)',
	`SHOW_ORDER_NUM` INT(3) NULL DEFAULT 1 COMMENT '표출우선순위',
	`SHOW_START_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '노출시작기간',
	`SHOW_END_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '노출종료기간',	
	`APPROVAL_STATUS` CHAR(1) NULL DEFAULT '1' COMMENT '승인상태(1 : 노출보류, 2 : 서비스(게시))',
	`CONTENTS` TEXT NULL DEFAULT NULL COMMENT '컨텐츠 내용',
	`USER_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '작성자 USER ID',	
	`USE_YN` CHAR(1) NULL DEFAULT 'Y' COMMENT '사용여부(Y : 사용, N : 미사용)',
	`REG_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자 ID',
	`REG_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`UPD_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자 ID',
	`UPD_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`ID`)
)
COMMENT='안내페이지 테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
