-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_IP_ADDRESS (
	SEQ					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT '아이피SEQ',
	USER_ID				VARCHAR(100)								COMMENT '사용자ID',
	IP					VARCHAR(100)								COMMENT '등록아이피',
	REG_USER        	VARCHAR(100)                             	COMMENT '등록자 ID',
	REG_DATE			DATETIME		DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
) COMMENT='사용자등록아이피';