-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_LEARN_APP (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT '수강신청 마스터 ID',
	USER_ID				VARCHAR(100)	NOT NULL					COMMENT '수강신청 유저',
	GROUP_ID			INT(12)										COMMENT '단체연수 ID 없는 경우 단체 연수 신청 아님',
	CARDINAL_ID			VARCHAR(12)		NOT NULL					COMMENT '기수 ID(n999999999 경우 자율 연수)',
	COURSE_ID			VARCHAR(12)		NOT NULL					COMMENT '과정 ID',
	NEIS_NUM			VARCHAR(20)									COMMENT 'NEIS 개인번호',
	DES_NUM				VARCHAR(20)									COMMENT '연수지명번호',
	SCHOOL_NAME			VARCHAR(255)								COMMENT '학교/기관명',
	TEL					VARCHAR(50)									COMMENT '연락처',
	PHONE				VARCHAR(50)									COMMENT '핸드폰',
	EMAIL				VARCHAR(100)								COMMENT '이메일',
	REGION_CODE			VARCHAR(12)									COMMENT '지역 시도 교육청 분류 코드',
	JURISDICTION		VARCHAR(50)									COMMENT '관할교육청',
	S_TYPE				CHAR(1)										COMMENT '학교구분(1:초등, 2:중학교, 3:고등학교, 4:유치원, 5:특수학교, 6:기관)',
	E_TYPE				CHAR(1)										COMMENT '설립구분(1:국립, 2:공립, 3:사립)',
	POST_TYPE			CHAR(1)			DEFAULT 'O'					COMMENT '우편수령지(H:집, O:학교/사무실)',
	MAIN_BOOK			INT(3)			DEFAULT 0					COMMENT '주교재신청갯수',
	SUB_BOOK			INT(3)			DEFAULT 0					COMMENT '교구신청갯수',
	ORDER_IDX			VARCHAR(20)									COMMENT '주문번호(결제내역의 ORDER_IDXX와 동일)',
	PAYMENT_TYPE		CHAR(1)			DEFAULT '1'					COMMENT '결제방식(1:무통장입금, 2:계좌이체, 3:가상계좌, 4:신용카드, 5:지난연기결제, 6:무료, 7:단체연수결제)',
	PAYMENT_STATE		CHAR(1)			DEFAULT '1'					COMMENT '결제상태(1:미결제, 2:결제완료, 3:일부결제, 4:환불)',
	PAYMENT_DATE		VARCHAR(14)									COMMENT '결제확인일시',
	APP_NUM				VARCHAR(100)								COMMENT '결제승인번호(카드??)',
	COUPON_NUM			VARCHAR(20)									COMMENT '쿠폰번호(결제완료 시 해당 쿠폰을 사용 완료 상태로 변경 시킴)',
	DIS_COUPON			INT(10)			DEFAULT 0					COMMENT '쿠폰할인금액',
	DIS_POINT			INT(10)			DEFAULT 0					COMMENT '포인트할인금액',
	DIS_GROUP			INT(10)			DEFAULT 0					COMMENT '단체할인금액',
	PAYMENT				INT(10)			DEFAULT 0					COMMENT '결제금액',
	REAL_PAYMENT		INT(10)			DEFAULT 0					COMMENT '실납입금액',
	REAL_END_DATE		VARCHAR(10)									COMMENT '실제 수강 종료일(연수종료일보다 크게 넣으면 그 기간 동안은 복습이 됨)',
	REQ_TYPE			CHAR(1)										COMMENT '요청구분(1:연기요청, 2:취소요청, 3:수강연기, 4:수강취소)',
	REQ_MEMO			VARCHAR(255)								COMMENT '요청사유',
	REQ_DATE			VARCHAR(10)									COMMENT '요청일자(연기 및 취소 요청일자)',
	ISSUE_YN			CHAR(1)			DEFAULT 'N'					COMMENT '이수처리 여부(Y/N)',
	ISSUE_DATE			VARCHAR(14)									COMMENT '이수처리 일자(재이수 시 재이수 날짜로 변경)',
	PART_SCORE			INT(3)			DEFAULT 0					COMMENT '학습참여도(이수 처리 시 적용)',
	TOTAL_SCORE			INT(3)			DEFAULT 0					COMMENT '최종성적(진도율+온라인평가+온라인과제+출석평가(4학점이상)을 집계',
	ISSUE_NUM			VARCHAR(50)									COMMENT '이수번호(이수시 이수번호 발급)',
	RECOMM_ID			VARCHAR(100)								COMMENT '추천인 ID',
	ORDER_NUM			INT(3)			DEFAULT 1					COMMENT '순서(필요없음)',
	USE_YN				CHAR(1)			DEFAULT 'Y'					COMMENT '사용여부(Y : 사용, N : 미사용)',
	REG_USER        	VARCHAR(100)                             	COMMENT '등록자 ID',
	REG_DATE			VARCHAR(14)									COMMENT '등록일자',
  	UPD_USER        	VARCHAR(100)                             	COMMENT '수정자 ID',
	UPD_DATE		  	VARCHAR(14)									COMMENT '수정일자'
) COMMENT='수강신청 관리 테이블';