-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_MEMBER_OUT (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT 'MEMBER 탈퇴 ID',
	USER_ID				VARCHAR(100)	NOT NULL					COMMENT 'MEMBER ID',
	NOTE				VARCHAR(500)								COMMENT '사유/비고',
	USE_YN				CHAR(1)			DEFAULT 'Y'					COMMENT '사용여부(Y : 사용, N : 미사용)',
	REG_DATE			DATETIME		DEFAULT CURRENT_TIMESTAMP()	COMMENT '등록일자'
) COMMENT='탈퇴회원 관리 TABLE';