CREATE TABLE CB_PAYMENT_KCP
    (
    ID				    INT(12)		NOT NULL AUTO_INCREMENT 	COMMENT '결제 ID',
    REQ_TX                          VARCHAR(3)		NOT NULL	COMMENT '요청구분',
    USE_PAY_METHOD                  VARCHAR(12)		NOT NULL	COMMENT '사용결제수단',
    BSUCC                           VARCHAR(20)					COMMENT '업체DB정상처리완료여부',
    RES_CD                          VARCHAR(5)					COMMENT '결과코드',
    RES_MSG                         VARCHAR(100)				COMMENT '결과메시지',
    AMOUNT                          INT(10)		NOT NULL		COMMENT '금액',
    ORDR_IDXX                       VARCHAR(40)		NOT NULL	COMMENT '주문번호',
    TNO                             VARCHAR(14)		NOT NULL	COMMENT 'KCP거래번호',
    GOOD_MNY                        INT(10)		NOT NULL		COMMENT '결제금액',
    GOOD_NAME                       VARCHAR(500)				COMMENT '상품명',
    BUYR_NAME                       VARCHAR(30)		NOT NULL	COMMENT '구매자명',
    BUYR_TEL1                       VARCHAR(20)					COMMENT '구매자전화번호',
    BUYR_TEL2                       VARCHAR(20)					COMMENT '구매자휴대폰번호',
    BUYR_MAIL                       VARCHAR(50)					COMMENT '구매자EMAIL',
    APP_TIME                        VARCHAR(14)					COMMENT '공통-승인시간',
    CARD_CD                         VARCHAR(4)					COMMENT '신용카드-카드코드',
    CARD_NAME                       VARCHAR(32)					COMMENT '신용카드-카드명',
    NOINF                           VARCHAR(1)					COMMENT '신용카드-무이자여부',
    QUOTA                           VARCHAR(2)					COMMENT '신용카드-할부개월',
    APP_NO                          VARCHAR(8)					COMMENT '신용카드-승인번호',
    PARTCANC_YN                     VARCHAR(1)					COMMENT '신용카드-부분취소가능여부',
    CARD_MNY                     	VARCHAR(20)					COMMENT '신용카드-카드결제금액',
    BANK_NAME                       VARCHAR(20)					COMMENT '계좌이체-은행명',
    BANK_CODE                       VARCHAR(4)					COMMENT '계좌이체-은행코드',
    BK_MNY                       	VARCHAR(20)					COMMENT '계좌이체-결제금액',
    BANKNAME                        VARCHAR(20)					COMMENT '가상계좌-입금할은행',
    DEPOSITOR                       VARCHAR(50)					COMMENT '가상계좌-입금할계좌예금주',
    ACCOUNT                         VARCHAR(20)					COMMENT '가상계좌-입금할계좌번호',
    VA_DATE                         VARCHAR(14)					COMMENT '가상계좌-가상계좌입금마감시간',
    PNT_ISSUE                       VARCHAR(20)					COMMENT '공통-포인트서비스사',
    PNT_AMOUNT                      INT(10)						COMMENT '포인트-적립금액/사용금액',
    PNT_APP_TIME                    VARCHAR(14)					COMMENT '포인트-승인시간',
    PNT_APP_NO                      VARCHAR(20)					COMMENT '포인트-승인번호',
    ADD_PNT                         INT(10)						COMMENT '포인트-발생포인트',
    USE_PNT                         INT(10)						COMMENT '포인트-사용가능포인트',
    RSV_PNT                         INT(10)						COMMENT '포인트-적립포인트',
    COMMID                          VARCHAR(3)					COMMENT '휴대폰-통신사코드',
    MOBILE_NO                       VARCHAR(11)					COMMENT '휴대폰-휴대폰번호',
    TK_VAN_CODE                     VARCHAR(4)					COMMENT '상품권-발급사코드',
    TK_APP_NO                       VARCHAR(20)					COMMENT '상품권-승인번호',
    CASH_YN                         VARCHAR(1)					COMMENT '현금영수증-등록여부',
    CASH_AUTHNO                     VARCHAR(9)					COMMENT '현금영수증-승인번호',
    CASH_TR_CODE                    VARCHAR(1)					COMMENT '현금영수증-발행구분',
    CASH_ID_INFO                    VARCHAR(13)					COMMENT '현금영수증-등록번호',
    CASH_NO                       	VARCHAR(14)					COMMENT '현금 영수증-거래 번호',
    REG_USER			    VARCHAR(100)							COMMENT '등록자 ID',
    REG_DATE			    DATETIME	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시',
    UPD_USER			    VARCHAR(100)							COMMENT '수정자 ID',
    UPD_DATE			    DATETIME	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일시',
    PRIMARY KEY (ID)
    ) COMMENT = '결제내역_KCP';
