-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_POINT (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT 'POINT ID',
	USER_ID				VARCHAR(100)	NOT NULL					COMMENT '수강자ID',
	LEARN_APP_ID		INT(12)										COMMENT '연수신청ID',
	NAME				VARCHAR(100)								COMMENT '이름',
	GIVE				INT(10)			DEFAULT 0					COMMENT '적립포인트',
	WITHDRAW			INT(10)			DEFAULT 0					COMMENT '회수포인트',
	NOTE				VARCHAR(255)								COMMENT '비고(사유)',
	REG_DATE			VARCHAR(14)									COMMENT '등록일자'
) COMMENT='포인트 관리 테이블';