-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE `CB_POLICY_POINT` (
   `ID` INT(12) NOT NULL AUTO_INCREMENT COMMENT '포인트 정책 ID',
   `SAVE_JOIN_POINT` INT(10) NULL DEFAULT NULL COMMENT '신규회원가입시 적립 포인트',
   `SAVE_JOIN_USE` CHAR(1) NULL DEFAULT 'Y' COMMENT '신규회원가입시 적립 사용유무',   
   `SAVE_LECTURE_POINT` INT(10) NULL DEFAULT NULL COMMENT '수강신청시 적립 포인트',
   `SAVE_LECTURE_TYPE` CHAR(1) NULL DEFAULT '1' NULL COMMENT '(1:점, 2:퍼센트)',
   `SAVE_LECTURE_USE` CHAR(1) NULL DEFAULT 'Y' COMMENT '수강신청시 적립 사용유무',      
   `SAVE_TRAIN_POINT` INT(10) NULL DEFAULT NULL COMMENT '연수후기작성시 적립 포인트',
   `SAVE_TRAIN_USE` CHAR(1) NULL DEFAULT 'Y' COMMENT '연수후기작성시 적립 사용유무',         
   `USE_LECTURE_POINT` INT(10) NULL DEFAULT NULL COMMENT '수강신청시 사용시 포인트(부터)',
   `USE_LECTURE_UNIT` INT(10) NULL DEFAULT NULL COMMENT '수강신청시 사용시 단위(로 사용)',   
   `USE_LECTURE_USE` CHAR(1) NULL DEFAULT 'Y' COMMENT '수강신청시 사용시 사용유무',
   `USE_YN` CHAR(1) NULL DEFAULT 'Y' COMMENT '사용여부(Y : 사용, N : 미사용)',
   `REG_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자 ID',
   `REG_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '등록일자',
   `UPD_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자 ID',
   `UPD_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '수정일자',   
   PRIMARY KEY (ID)
) COMMENT='포인트 정책 테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;