-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE `CB_POLICY_DELAY_CANCEL` (
   `ID` INT(12) NOT NULL AUTO_INCREMENT COMMENT '수강연기/취소 정책 ID',
   `DELAY_COURSE_DAY` INT(10) NULL DEFAULT NULL COMMENT '연기정책_과정신청일로부터 (~이내)',   
   `DELAY_TRAIN_DAY` INT(10) NULL DEFAULT NULL COMMENT '연기정책_연수시작일로부터 (~이내)',
   `CANCEL_COURSE_DAY` INT(10) NULL DEFAULT NULL COMMENT '취소정책_과정신청일로부터 (~이내)',   
   `CANCEL_TRAIN_DAY` INT(10) NULL DEFAULT NULL COMMENT '취소정책_연수시작일로부터 (~이내)',
   `USE_YN` CHAR(1) NULL DEFAULT 'Y' COMMENT '사용여부(Y : 사용, N : 미사용)',
   `REG_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자 ID',
   `REG_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '등록일자',
   `UPD_USER` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자 ID',
   `UPD_DATE` VARCHAR(14) NULL DEFAULT NULL COMMENT '수정일자',   
   PRIMARY KEY (ID)
) COMMENT='수강 연기/취소 정책 테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;