/** LG U+ SMS 문자발송 임시 테이블 **/
CREATE TABLE SC_TRAN
(
	TR_NUM			INT				NOT NULL		AUTO_INCREMENT,
	TR_SENDDATE	DATETIME,
	TR_ID				VARCHAR(16),
	TR_SENDSTAT	VARCHAR(1)		NOT NULL	 DEFAULT'0',
	TR_RSLTSTAT	VARCHAR(2)		DEFAULT'00',
	TR_MSGTYPE	VARCHAR(1)		NOT NULL	 DEFAULT'0',
	TR_PHONE		VARCHAR(20)		NOT NULL	 DEFAULT'',
	TR_CALLBACK	VARCHAR(20),
	TR_RSLTDATE	DATETIME,
	TR_MODIFIED	DATETIME,
	TR_MSG			VARCHAR(160),
	TR_NET			VARCHAR(4),
	TR_ETC1			VARCHAR(160),
	TR_ETC2			VARCHAR(160),
	TR_ETC3			VARCHAR(160),
	TR_ETC4			VARCHAR(160),
	TR_ETC5			VARCHAR(160),
	TR_ETC6			VARCHAR(160),
	TR_ROUTEID		VARCHAR(20),
	TR_REALSENDDATE		DATETIME,
	CONSTRAINT PK_SC_TRAN PRIMARY KEY CLUSTERED ( TR_NUM )
) COLLATE='utf8_general_ci'