-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE CB_SMS_HISTORY (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT 'SMS 이력 ID',
	USER_ID				VARCHAR(100)	NOT NULL					COMMENT '수신자 ID',
	PHONE				VARCHAR(50)		NOT NULL					COMMENT '핸드폰',
	SUBJECT				VARCHAR(100)	NOT NULL					COMMENT '제목',
	CONTENT				VARCHAR(2000)	NOT NULL					COMMENT '내용',
	REG_ID				VARCHAR(100)	NOT NULL					COMMENT '발신자 ID',
	REG_DATE			VARCHAR(14)									COMMENT '종료일시'
) COMMENT='SMS 이력 관리 테이블';