CREATE TABLE CB_TEACHER_APP (
	ID				INT(12)	NOT			NULL AUTO_INCREMENT		COMMENT '제휴문의 마스터 ID',
	USER_ID			VARCHAR(100)		NULL  					COMMENT '지원 유저',
	NAME			VARCHAR(100)		NOT NULL				COMMENT '성명',
	PHONE			VARCHAR(50)			NULL DEFAULT NULL		COMMENT '연락처',
	EMAIL			VARCHAR(100)		NULL DEFAULT NULL		COMMENT '이메일',
	COURSES			VARCHAR(100)		NULL DEFAULT NULL		COMMENT '과정타입명리스트(콤마분리)',
	COMMENT			MEDIUMTEXT			NULL DEFAULT NULL		COMMENT '자기소개',
	ATTACH1_FILE	VARCHAR(20)			NULL DEFAULT NULL		COMMENT '첨부 #1 파일',
	ATTACH2_FILE	VARCHAR(20)			NULL DEFAULT NULL		COMMENT '첨부 #2 파일',
	USE_YN			CHAR(1)				NULL DEFAULT 'Y'		COMMENT '사용여부(Y : 사용, N : 미사용)',
	REG_USER		VARCHAR(100)		NULL DEFAULT NULL		COMMENT '등록자 ID',
	REG_DATE		VARCHAR(14)			NULL DEFAULT NULL		COMMENT '등록일자',
	UPD_USER		VARCHAR(100)		NULL DEFAULT NULL		COMMENT '수정자 ID',
	UPD_DATE		VARCHAR(14)			NULL DEFAULT NULL		COMMENT '수정일자',
	PRIMARY KEY (ID)
)
COMMENT='강사신청 테이블';