ALTER TABLE BOGUN.T_ATT_LEC_HISTORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_ATT_LEC_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_ATT_LEC_HISTORY
(
  ID            NUMBER(12)                      NOT NULL,
  LEARN_APP_ID  NUMBER(12)                      NOT NULL,
  USER_ID       VARCHAR2(100 BYTE)              NOT NULL,
  COURSE_ID     VARCHAR2(12 BYTE)               NOT NULL,
  CARDINAL_ID   NUMBER(12)		                NOT NULL,
  CHAPTER_ID	NUMBER(12)                      NOT NULL,
  CHASI         NUMBER(3)                       DEFAULT '1',
  PAGE			NUMBER(3)						DEFAULT '1',
  START_DATE    VARCHAR2(14 BYTE)               DEFAULT NULL,
  END_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_ATT_LEC_HISTORY IS '수강 이력 관리 테이블';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.ID IS '수강 이력 ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.LEARN_APP_ID IS '수강신청ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.USER_ID IS '수강자ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.COURSE_ID IS '과정ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.CARDINAL_ID IS '기수ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.CHAPTER_ID IS '챕터ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.CHASI IS '차시(순서 1차시~30차시)';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.PAGE IS '차시 별 PAGE 번호';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.START_DATE IS '시작일시';

COMMENT ON COLUMN BOGUN.T_ATT_LEC_HISTORY.END_DATE IS '종료일시';


--  There is no statement for index BOGUN.SYS_C0010375.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_ATT_LEC_HISTORY ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_ATT_LEC_HISTORY;
  
  CREATE SEQUENCE SEQ_ATT_LEC_HISTORY INCREMENT BY 1 START WITH 1;