ALTER TABLE BOGUN.T_ATT_LEC
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_ATT_LEC CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_ATT_LEC
(
  ID            NUMBER(12)                      NOT NULL,
  LEARN_APP_ID  NUMBER(12)                      NOT NULL,
  USER_ID       VARCHAR2(100 BYTE)              NOT NULL,
  COURSE_ID     VARCHAR2(12 BYTE)               NOT NULL,
  CARDINAL_ID   NUMBER(12)               		NOT NULL,
  CHAPTER_ID    NUMBER(12)                      NOT NULL,
  CHASI         NUMBER(3)                       DEFAULT '1',
  PAGE			NUMBER(3)						DEFAULT '1',
  STUDY         NUMBER(2)                       DEFAULT '0',
  CHK           NUMBER(2)                       DEFAULT '0',
  LEARN_TIME    NUMBER(10)                      DEFAULT '0',
  PROG_YN       CHAR(1 BYTE)                    DEFAULT 'N'
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_ATT_LEC IS '수강 이력 상세 관리 테이블';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.ID IS '수강 이력 ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.LEARN_APP_ID IS '수강신청ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.USER_ID IS '수강자ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.COURSE_ID IS '과정ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.CARDINAL_ID IS '기수ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.CHAPTER_ID IS '챕터ID';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.CHASI IS '차시(순서 1차시~30차시)';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.PAGE IS '차시 별 PAGE 번호';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.STUDY IS '교육시간(분)';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.CHK IS '체크(분)';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.LEARN_TIME IS '학습시간(초단위)';

COMMENT ON COLUMN BOGUN.T_ATT_LEC.PROG_YN IS '차시별 체크(분)가 지나면 Y로 변경 시켜줌(진도 완료)';


--  There is no statement for index BOGUN.SYS_C0010368.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_ATT_LEC ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_ATT_LEC;
  
  CREATE SEQUENCE SEQ_ATT_LEC INCREMENT BY 1 START WITH 1;