ALTER TABLE BOGUN.T_ATTACH_FILE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_ATTACH_FILE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_ATTACH_FILE_DETAIL
(
  FILE_ID           VARCHAR2(20 BYTE)           NOT NULL,
  FILE_NAME         VARCHAR2(100 BYTE)          NOT NULL,
  ORIGIN_FILE_NAME  VARCHAR2(255 BYTE)          DEFAULT NULL,
  FILE_PATH         VARCHAR2(255 BYTE)          NOT NULL,
  FILE_EXT          VARCHAR2(20 BYTE)           NOT NULL,
  FILE_SIZE         NUMBER(12)                  DEFAULT '0',
  URL_PATH          VARCHAR2(255 BYTE)          DEFAULT NULL,
  ORDER_NUM         NUMBER(3)                   DEFAULT '1'
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_ATTACH_FILE_DETAIL IS 'ATTACHFILE DETAIL TABLE';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.FILE_ID IS '파일 ID';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.FILE_NAME IS '파일명';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.ORIGIN_FILE_NAME IS '원본 파일명';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.FILE_PATH IS '파일 경로';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.FILE_EXT IS '파일 확장자';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.FILE_SIZE IS '파일 사이즈';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.URL_PATH IS '파일 URL 호출 경로';

COMMENT ON COLUMN BOGUN.T_ATTACH_FILE_DETAIL.ORDER_NUM IS '파일 DISPLAY순서(같은 파일 ID별 순서)';


--  There is no statement for index BOGUN.SYS_C0010506.
--  The object is created when the parent object is created.

--  There is no statement for index BOGUN.SYS_C0010507.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_ATTACH_FILE_DETAIL ADD (
  PRIMARY KEY
  (FILE_ID, FILE_NAME)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);