ALTER TABLE BOGUN.T_BOARD_COMMENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_BOARD_COMMENT CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_BOARD_COMMENT
(
  ID        NUMBER(12)                          NOT NULL,
  BOARD_ID  NUMBER(12)                          NOT NULL,
  USER_ID   VARCHAR2(100 BYTE)                  DEFAULT NULL,
  CMNT      VARCHAR2(500 BYTE)                  DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_BOARD_COMMENT IS 'BOARD COMMENT TABLE';

COMMENT ON COLUMN BOGUN.T_BOARD_COMMENT.ID IS '댓글 마스터 ID(SEQ로 ID저장)';

COMMENT ON COLUMN BOGUN.T_BOARD_COMMENT.BOARD_ID IS '게시글 ID';

COMMENT ON COLUMN BOGUN.T_BOARD_COMMENT.USER_ID IS '작성자 USER ID(사용자가 답글 남긴 경우)';

COMMENT ON COLUMN BOGUN.T_BOARD_COMMENT.CMNT IS '댓글 내용';


--  There is no statement for index BOGUN.SYS_C0010381.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_BOARD_COMMENT ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_BOARD_COMMENT;
  
  CREATE SEQUENCE SEQ_BOARD_COMMENT INCREMENT BY 1 START WITH 1;