ALTER TABLE BOGUN.T_BOARD_REPLY
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_BOARD_REPLY CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_BOARD_REPLY
(
  ID            NUMBER(12)                      NOT NULL,
  BOARD_ID      NUMBER(12)                      NOT NULL,
  PARENT_ID     NUMBER(12)                      DEFAULT NULL,
  USER_ID       VARCHAR2(100 BYTE)              DEFAULT NULL,
  DEPTH         NUMBER(3)                       DEFAULT '1',
  ATTACH1_FILE  VARCHAR2(20 BYTE)               DEFAULT NULL,
  ATTACH2_FILE  VARCHAR2(20 BYTE)               DEFAULT NULL,
  TITLE         VARCHAR2(255 BYTE)              DEFAULT NULL,
  CMNT          CLOB,
  HITS          NUMBER(8)                       DEFAULT '0',
  RECOMMEND     NUMBER(8)                       DEFAULT '0',
  NONRECOMMEND  NUMBER(8)                       DEFAULT '0',
  SHARED        NUMBER(8)                       DEFAULT '0',
  ORDER_NUM     NUMBER(3)                       DEFAULT '1',
  USE_YN        CHAR(1 BYTE)                    DEFAULT 'Y',
  REG_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  REG_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL,
  UPD_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  UPD_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_BOARD_REPLY IS 'BOARD MASTER TABLE';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.ID IS '답글 마스터 ID(SEQ로 ID저장)';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.BOARD_ID IS '게시글 ID';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.PARENT_ID IS '부모 답글 ID(답글에 답글을 다는 경우)';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.USER_ID IS '작성자 USER ID(사용자가 답글 남긴 경우)';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.DEPTH IS '답글 뎁스';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.ATTACH1_FILE IS '첨부 #1 파일';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.ATTACH2_FILE IS '첨부 #2 파일';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.TITLE IS '게시물 제목';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.CMNT IS '게시물 내용';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.HITS IS '조회수';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.RECOMMEND IS '추천수';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.NONRECOMMEND IS '비추천수';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.SHARED IS '공유횟수';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.ORDER_NUM IS 'DISPLAY순서(게시판 기준으로 ORDER)';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_BOARD_REPLY.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010384.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_BOARD_REPLY ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_BOARD_REPLY;
  
  CREATE SEQUENCE SEQ_BOARD_REPLY INCREMENT BY 1 START WITH 1;