ALTER TABLE BOGUN.T_CODE_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_CODE_GROUP CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_CODE_GROUP
(
  ID         VARCHAR2(20 BYTE)                  NOT NULL,
  NAME       VARCHAR2(255 BYTE)                 NOT NULL,
  CMNT       VARCHAR2(255 BYTE)                 DEFAULT NULL,
  ORDER_NUM  NUMBER(3)                          DEFAULT '1',
  USE_YN     CHAR(1 BYTE)                       DEFAULT 'Y',
  REG_USER   VARCHAR2(100 BYTE)                 DEFAULT NULL,
  REG_DATE   VARCHAR2(14 BYTE)                  DEFAULT NULL,
  UPD_USER   VARCHAR2(100 BYTE)                 DEFAULT NULL,
  UPD_DATE   VARCHAR2(14 BYTE)                  DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_CODE_GROUP IS 'CODE GROUP TABLE(분류 코드 관리)';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.ID IS 'CODE 그룹 ID';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.NAME IS 'CODE 그룹 명';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.CMNT IS 'CODE 그룹 설명';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.ORDER_NUM IS '분류 그룹 별 순서';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_CODE_GROUP.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010516.
--  The object is created when the parent object is created.

--  There is no statement for index BOGUN.SYS_C0010517.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_CODE_GROUP ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);