ALTER TABLE BOGUN.T_COURSE
 DROP PRIMARY KEY CASCADE;
 
DROP TABLE BOGUN.T_COURSE CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_COURSE
(
  ID              VARCHAR2(12 BYTE)             NOT NULL,
  CATE_ID         NUMBER(12)                    NOT NULL,
  ONOFF_TYPE      VARCHAR2(1 BYTE)              NOT NULL,
  COM_ID          VARCHAR2(100 BYTE)            DEFAULT NULL,
  COM_CAL         VARCHAR2(5 BYTE)              DEFAULT NULL,
  TEACH_ID        VARCHAR2(100 BYTE)            DEFAULT NULL,
  TEACH_CAL       VARCHAR2(5 BYTE)              DEFAULT NULL,
  TUTOR_CAL       VARCHAR2(5 BYTE)              DEFAULT NULL,
  NAME            VARCHAR2(100 BYTE)            DEFAULT NULL,
  MAIN_YN         CHAR(1 BYTE)                  DEFAULT 'N',
  MAIN_DISPLAY    CHAR(1 BYTE)                  DEFAULT NULL,
  ICON_DISPLAYS   VARCHAR2(20 BYTE)             DEFAULT NULL,
  COMPLETE_TIME   NUMBER(3)                     DEFAULT '0',
  TARGET_TYPES    VARCHAR2(20 BYTE)             DEFAULT NULL,
  LEARN_TARGET    VARCHAR2(200 BYTE)            DEFAULT NULL,
  PRICE_YN        NUMBER(10)                    DEFAULT '0',
  PRICE_INFO      VARCHAR2(100 BYTE)            DEFAULT NULL,
  PROG_CHECK      NUMBER(2)                     DEFAULT '0',
  OPEN_DATE       VARCHAR2(10 BYTE)             DEFAULT NULL,
  APP_DATE        VARCHAR2(10 BYTE)             DEFAULT NULL,
  RECRUIT         NUMBER(3)                     DEFAULT '0',
  EXAM_PERIOD     NUMBER(3)                     DEFAULT '1',
  LINK_SERVER     NUMBER(3)                     DEFAULT '1',
  MOBILE_YN       CHAR(1 BYTE)                  DEFAULT 'N',
  INDEX_URL       VARCHAR2(500 BYTE)            DEFAULT NULL,
  TASTING_URL     VARCHAR2(500 BYTE)            DEFAULT 'NULL',
  SAMPLE_URL      VARCHAR2(500 BYTE)            DEFAULT NULL,
  WIDTH           VARCHAR2(4 BYTE)              DEFAULT NULL,
  HEIGHT          VARCHAR2(4 BYTE)              DEFAULT NULL,
  SELP_PERIOD     NUMBER(3)                     DEFAULT '0',
  MAIN_IMG_FILE   VARCHAR2(20 BYTE)             DEFAULT NULL,
  ACCEPT_YN       CHAR(1 BYTE)                  DEFAULT 'N',
  PURPOSE         VARCHAR2(4000 BYTE),
  SUMMARY         VARCHAR2(4000 BYTE),
  INSTRUCTOR      VARCHAR2(4000 BYTE),
  NOTE            VARCHAR2(4000 BYTE),
  MOBILE_SUMMARY  VARCHAR2(4000 BYTE),
  DEVELOPER       VARCHAR2(50 BYTE)             DEFAULT NULL,
  RES_TEL         VARCHAR2(50 BYTE)             DEFAULT NULL,
  COM_NAME        VARCHAR2(50 BYTE)             DEFAULT NULL,
  COM_TEL         VARCHAR2(50 BYTE)             DEFAULT NULL,
  PRODUCE_DATE    VARCHAR2(10 BYTE)             DEFAULT NULL,
  STORAGE_LOC     VARCHAR2(100 BYTE)            DEFAULT NULL,
  HISTORY         VARCHAR2(4000 BYTE),
  REMARKS         VARCHAR2(4000 BYTE),
  ORDER_NUM       NUMBER(3)                     DEFAULT '1',
  HITS_ORDER      NUMBER(10)                    DEFAULT '1',
  USE_YN          CHAR(1 BYTE)                  DEFAULT 'Y',
  REG_USER        VARCHAR2(100 BYTE)            DEFAULT NULL,
  REG_DATE        VARCHAR2(14 BYTE)             DEFAULT NULL,
  UPD_USER        VARCHAR2(100 BYTE)            DEFAULT NULL,
  UPD_DATE        VARCHAR2(14 BYTE)             DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_COURSE IS '연수과정 관리 테이블';

COMMENT ON COLUMN BOGUN.T_COURSE.ID IS '연수과정 ID';

COMMENT ON COLUMN BOGUN.T_COURSE.CATE_ID IS '과정 카테고리 ID';

COMMENT ON COLUMN BOGUN.T_COURSE.ONOFF_TYPE IS '온오프라인교육 타입';

COMMENT ON COLUMN BOGUN.T_COURSE.COM_ID IS '업체 ID(관리자처럼 관리)';

COMMENT ON COLUMN BOGUN.T_COURSE.COM_CAL IS '업체 정산지급(%)';

COMMENT ON COLUMN BOGUN.T_COURSE.TEACH_ID IS '강사 ID(관리자처럼 관리)';

COMMENT ON COLUMN BOGUN.T_COURSE.TEACH_CAL IS '강사 정산지급(%)';

COMMENT ON COLUMN BOGUN.T_COURSE.TUTOR_CAL IS '튜터 정산지급(%)';

COMMENT ON COLUMN BOGUN.T_COURSE.NAME IS '과정명';

COMMENT ON COLUMN BOGUN.T_COURSE.MAIN_YN IS '메인표시여부';

COMMENT ON COLUMN BOGUN.T_COURSE.MAIN_DISPLAY IS '메인표시(1:창비추천, 2:초등추천, 3:중등추천)';

COMMENT ON COLUMN BOGUN.T_COURSE.ICON_DISPLAYS IS '아이콘표시 다중표시(1:NEW, 2:BEST, 3:인기, 4:업그레이드, 5:우수) - 다중선택';

COMMENT ON COLUMN BOGUN.T_COURSE.COMPLETE_TIME IS '이수시간';

COMMENT ON COLUMN BOGUN.T_COURSE.TARGET_TYPES IS '대상타입(1:유아, 2:초등, 3:중등, 4:전문직) - 다중 선택';

COMMENT ON COLUMN BOGUN.T_COURSE.LEARN_TARGET IS '연수대상';

COMMENT ON COLUMN BOGUN.T_COURSE.PRICE_YN IS '유료교육여부';

COMMENT ON COLUMN BOGUN.T_COURSE.PRICE_INFO IS '수강료안내';

COMMENT ON COLUMN BOGUN.T_COURSE.PROG_CHECK IS '진도체크(차시당 분)';

COMMENT ON COLUMN BOGUN.T_COURSE.OPEN_DATE IS '과정오픈일';

COMMENT ON COLUMN BOGUN.T_COURSE.APP_DATE IS '심사신청일';

COMMENT ON COLUMN BOGUN.T_COURSE.RECRUIT IS '모집인원';

COMMENT ON COLUMN BOGUN.T_COURSE.EXAM_PERIOD IS '시험교시(4학점 출석시험인 경우 사용)';

COMMENT ON COLUMN BOGUN.T_COURSE.LINK_SERVER IS '창비링크서버(1~2)';

COMMENT ON COLUMN BOGUN.T_COURSE.MOBILE_YN IS '모바일 서비스 여부';

COMMENT ON COLUMN BOGUN.T_COURSE.INDEX_URL IS '인덱스';

COMMENT ON COLUMN BOGUN.T_COURSE.TASTING_URL IS '미리보기';

COMMENT ON COLUMN BOGUN.T_COURSE.SAMPLE_URL IS '교재샘플';

COMMENT ON COLUMN BOGUN.T_COURSE.WIDTH IS '넓이';

COMMENT ON COLUMN BOGUN.T_COURSE.HEIGHT IS '높이';

COMMENT ON COLUMN BOGUN.T_COURSE.SELP_PERIOD IS '자율 연수인 경우 연수기간(인증일로부터 00일)';

COMMENT ON COLUMN BOGUN.T_COURSE.MAIN_IMG_FILE IS '대표 이미지 파일';

COMMENT ON COLUMN BOGUN.T_COURSE.ACCEPT_YN IS '접수상태';

COMMENT ON COLUMN BOGUN.T_COURSE.PURPOSE IS '과정목표';

COMMENT ON COLUMN BOGUN.T_COURSE.SUMMARY IS '과정개요';

COMMENT ON COLUMN BOGUN.T_COURSE.INSTRUCTOR IS '강사진 안내';

COMMENT ON COLUMN BOGUN.T_COURSE.NOTE IS '유의사항';

COMMENT ON COLUMN BOGUN.T_COURSE.MOBILE_SUMMARY IS '모바일 과정개요';

COMMENT ON COLUMN BOGUN.T_COURSE.DEVELOPER IS '과정개발자';

COMMENT ON COLUMN BOGUN.T_COURSE.RES_TEL IS '담당전화';

COMMENT ON COLUMN BOGUN.T_COURSE.COM_NAME IS '제작업체명';

COMMENT ON COLUMN BOGUN.T_COURSE.COM_TEL IS '업체전화';

COMMENT ON COLUMN BOGUN.T_COURSE.PRODUCE_DATE IS '제작일';

COMMENT ON COLUMN BOGUN.T_COURSE.STORAGE_LOC IS '보관위치';

COMMENT ON COLUMN BOGUN.T_COURSE.HISTORY IS '제작히스토리';

COMMENT ON COLUMN BOGUN.T_COURSE.REMARKS IS '특이사항 및 비고';

COMMENT ON COLUMN BOGUN.T_COURSE.ORDER_NUM IS '순서(필요없음)';

COMMENT ON COLUMN BOGUN.T_COURSE.HITS_ORDER IS '인기순위';

COMMENT ON COLUMN BOGUN.T_COURSE.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_COURSE.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_COURSE.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_COURSE.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_COURSE.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010639.
--  The object is created when the parent object is created.

--  There is no statement for index BOGUN.SYS_C0010640.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_COURSE ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);