ALTER TABLE BOGUN.T_COURSE_CATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_COURSE_CATE CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_COURSE_CATE
(
  ID          NUMBER(12)                        NOT NULL,
  NAME        VARCHAR2(100 BYTE)                NOT NULL,
  HTML        CLOB,
  ONOFF_TYPE  CHAR(1 BYTE)                      DEFAULT '1',
  ORDER_NUM   NUMBER(3)                         DEFAULT 1,
  USE_YN      CHAR(1 BYTE)                      DEFAULT 'Y',
  REG_USER    VARCHAR2(100 BYTE),
  REG_DATE    VARCHAR2(14 BYTE),
  UPD_USER    VARCHAR2(100 BYTE),
  UPD_DATE    VARCHAR2(14 BYTE)
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_COURSE_CATE IS '과정 카테고리 테이블';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.ID IS '과정카테고리 ID';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.NAME IS '과정카테고리명';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.HTML IS '과정카테고리 설명 HTML';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.ONOFF_TYPE IS '온라인/오프라인 구분(1 : 온라인, 2 : 오프라인)';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.ORDER_NUM IS '순서';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.USE_YN IS '사용여부(Y : 공개, N : 비공개)';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_COURSE_CATE.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010569.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_COURSE_CATE ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_COURSE_CATE;
  
  CREATE SEQUENCE SEQ_COURSE_CATE INCREMENT BY 1 START WITH 1;