ALTER TABLE BOGUN.T_COURSE_CARDINAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_COURSE_CARDINAL CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_COURSE_CARDINAL
(
  ID                    NUMBER(12)              NOT NULL,
  COURSE_ID             VARCHAR2(12 BYTE)       NOT NULL,
  APP_START_DATE        VARCHAR2(10 BYTE)       DEFAULT NULL,
  APP_END_DATE          VARCHAR2(10 BYTE)       DEFAULT NULL,
  LEARN_START_DATE      VARCHAR2(10 BYTE)       DEFAULT NULL,
  LEARN_END_DATE        VARCHAR2(10 BYTE)       DEFAULT NULL,
  OFF_REGION_CODE       VARCHAR2(12 BYTE)       DEFAULT NULL,
  OFF_EDU_LOCACTION     VARCHAR2(200 BYTE)      DEFAULT NULL,
  OFF_LEARN_DATE        VARCHAR2(10 BYTE)       DEFAULT NULL,
  OFF_LEARN_START_TIME  VARCHAR2(4 BYTE)        DEFAULT NULL,
  OFF_LEARN_END_TIME    VARCHAR2(4 BYTE)        DEFAULT NULL,
  OFF_TARGET_MIN        NUMBER(5)               DEFAULT 0,
  OFF_TARGET_MAX        NUMBER(5)               DEFAULT 0,
  OFF_TARGET_CHOOSE     VARCHAR2(100 BYTE)      DEFAULT NULL,
  ISSUE_DATE            VARCHAR2(10 BYTE)       DEFAULT NULL,
  ATT_EVAL_DATE         VARCHAR2(10 BYTE)       DEFAULT NULL,
  ATT_EVAL_TIME         VARCHAR2(200 BYTE)      DEFAULT NULL,
  ATT_EXAM_TYPE         CHAR(1 BYTE)            DEFAULT 'A',
  CANCEL_LIMIT          NUMBER(2)               DEFAULT '0',
  DUP_LIMIT             NUMBER(2)               DEFAULT '0',
  ADD_EXAM_PERIOD       NUMBER(2)               DEFAULT '0',
  OPEN_RESULTS          VARCHAR2(20 BYTE)       DEFAULT NULL,
  APP_POSSIBLES         VARCHAR2(20 BYTE)       DEFAULT NULL,
  EXPECT_EXAM           CHAR(1 BYTE)            DEFAULT NULL,
  PREVIEW               NUMBER(2)               DEFAULT '2',
  COMPLATE_YN           CHAR(1 BYTE)            DEFAULT 'N',
  USE_YN                CHAR(1 BYTE)            DEFAULT 'Y',
  REG_USER              VARCHAR2(100 BYTE)      DEFAULT NULL,
  REG_DATE              VARCHAR2(14 BYTE)       DEFAULT NULL,
  UPD_USER              VARCHAR2(100 BYTE)      DEFAULT NULL,
  UPD_DATE              VARCHAR2(14 BYTE)       DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_COURSE_CARDINAL IS '과정 기수 관리 테이블';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.ID IS '과정 기수 관리 마스터 ID';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.COURSE_ID IS '과정 ID';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.APP_START_DATE IS '접수시작일';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.APP_END_DATE IS '접수종료일';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.LEARN_START_DATE IS '연수시작일';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.LEARN_END_DATE IS '연수종료일';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_REGION_CODE IS '오프라인 교육 지역코드';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_EDU_LOCACTION IS '오프라인 교육 장소';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_LEARN_DATE IS '오프라인 교육 일자';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_LEARN_START_TIME IS '오프라인 교육 시작 시간';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_LEARN_END_TIME IS '오프라인 교육 종료 시간';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_TARGET_MIN IS '오프라인 교육 최소 인원';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_TARGET_MAX IS '오프라인 교육 최대 인원';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OFF_TARGET_CHOOSE IS '오프라인 교육 대상선정방법 안내';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.ISSUE_DATE IS '이수발급일';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.ATT_EVAL_DATE IS '출석평가일자';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.ATT_EVAL_TIME IS '출석평가시간';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.ATT_EXAM_TYPE IS '출석고사장(A : 고사장숨김/변경신청불가, B : 고사장노출/변경신청가능, C : 고사장노출/변경신청불가)';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.CANCEL_LIMIT IS '수강취소가능기간(신청일로부터 1~10일)';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.DUP_LIMIT IS '기수내 다른 과정 신청 제한(1~10개)';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.ADD_EXAM_PERIOD IS '추가평가기간(1~5일) 온라인평가 과제제출기간에서 설정만큼 추가로 제출 가능';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.OPEN_RESULTS IS '학점별 성적 공개(1~4학점) 다중선택';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.APP_POSSIBLES IS '신청가능학점(1~4학점) 다중선택';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.EXPECT_EXAM IS '출석평가 예상문제(A~)';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.PREVIEW IS '예습미리보기(1~10강)';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.COMPLATE_YN IS '이수처리 여부';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_COURSE_CARDINAL.UPD_DATE IS '수정일자';


CREATE INDEX BOGUN.CARDINAL_NEW_IDX01 ON BOGUN.T_COURSE_CARDINAL
(COURSE_ID)
LOGGING
TABLESPACE BOGUN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--  There is no statement for index BOGUN.SYS_C0010649.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_COURSE_CARDINAL ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_COURSE_CARDINAL;
  
  CREATE SEQUENCE SEQ_COURSE_CARDINAL INCREMENT BY 1 START WITH 1;