ALTER TABLE BOGUN.T_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_INFO CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_INFO
(
  ID               NUMBER(12)                   NOT NULL,
  THEMA_TYPE       NUMBER(2)                    DEFAULT NULL,
  SHOW_ORDER_NUM   NUMBER(3)                    DEFAULT '1',
  SHOW_START_DATE  VARCHAR2(14 BYTE)            DEFAULT NULL,
  SHOW_END_DATE    VARCHAR2(14 BYTE)            DEFAULT NULL,
  APPROVAL_STATUS  CHAR(1 BYTE)                 DEFAULT '1',
  CONTENTS         VARCHAR2(4000 BYTE),
  USER_ID          VARCHAR2(100 BYTE)           DEFAULT NULL,
  USE_YN           CHAR(1 BYTE)                 DEFAULT 'Y',
  REG_USER         VARCHAR2(100 BYTE)           DEFAULT NULL,
  REG_DATE         VARCHAR2(14 BYTE)            DEFAULT NULL,
  UPD_USER         VARCHAR2(100 BYTE)           DEFAULT NULL,
  UPD_DATE         VARCHAR2(14 BYTE)            DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_INFO IS '안내페이지 테이블';

COMMENT ON COLUMN BOGUN.T_INFO.ID IS '안내 ID(SEQ로 ID저장)';

COMMENT ON COLUMN BOGUN.T_INFO.THEMA_TYPE IS '테마타입 (1 : 회원약관, 2 : 개인정보보호정책, 3 : 소개, 4 : 연혁, 5 : 조직도, 6 : 찾아오시는길, 7 : 규정, 8 : 교육부 인가서)';

COMMENT ON COLUMN BOGUN.T_INFO.SHOW_ORDER_NUM IS '표출우선순위';

COMMENT ON COLUMN BOGUN.T_INFO.SHOW_START_DATE IS '노출시작기간';

COMMENT ON COLUMN BOGUN.T_INFO.SHOW_END_DATE IS '노출종료기간';

COMMENT ON COLUMN BOGUN.T_INFO.APPROVAL_STATUS IS '승인상태(1 : 노출보류, 2 : 서비스(게시))';

COMMENT ON COLUMN BOGUN.T_INFO.CONTENTS IS '컨텐츠 내용';

COMMENT ON COLUMN BOGUN.T_INFO.USER_ID IS '작성자 USER ID';

COMMENT ON COLUMN BOGUN.T_INFO.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_INFO.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_INFO.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_INFO.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_INFO.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010401.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_INFO ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_INFO;
  
  CREATE SEQUENCE SEQ_INFO INCREMENT BY 1 START WITH 1;