ALTER TABLE BOGUN.T_LEARN_CANCEL_APP
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_LEARN_CANCEL_APP CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_LEARN_CANCEL_APP
(
  ID            NUMBER(12)                      NOT NULL,
  USER_ID       VARCHAR2(100 BYTE)              NOT NULL,
  LEARN_APP_ID  NUMBER(12)                      NOT NULL,
  TEL           VARCHAR2(50 BYTE)               DEFAULT NULL,
  PHONE         VARCHAR2(50 BYTE)               DEFAULT NULL,
  EMAIL         VARCHAR2(100 BYTE)              DEFAULT NULL,
  BOOK_TYPE     CHAR(1 BYTE)                    NOT NULL,
  BANK          VARCHAR2(50 BYTE)               NOT NULL,
  ACCOUNT       VARCHAR2(100 BYTE)              NOT NULL,
  OWNER         VARCHAR2(50 BYTE)               NOT NULL,
  MEMO          VARCHAR2(1000 BYTE)             DEFAULT NULL,
  STATE         CHAR(1 BYTE)                    DEFAULT '1',
  USE_YN        CHAR(1 BYTE)                    DEFAULT 'Y',
  REG_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  REG_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL,
  UPD_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  UPD_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_LEARN_CANCEL_APP IS '연수 취소신청 관리 테이블';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.ID IS '취소신청 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.USER_ID IS '신청자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.LEARN_APP_ID IS '수강신청 마스터 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.TEL IS '연락처';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.PHONE IS '핸드폰';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.EMAIL IS '전자우편';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.BOOK_TYPE IS '교제구매여부(1:구매, 2:반송)';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.BANK IS '환불은행';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.ACCOUNT IS '환불계좌';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.OWNER IS '환불예금주';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.MEMO IS '취소사용';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.STATE IS '취소신청상태(1:신청(접수 처리중), 2:취소완료, 3:취소불가)';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CANCEL_APP.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010416.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_LEARN_CANCEL_APP ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_LEARN_CANCEL_APP;
  
  CREATE SEQUENCE SEQ_LEARN_CANCEL_APP INCREMENT BY 1 START WITH 1;