ALTER TABLE BOGUN.T_LEARN_CHANGE_APP
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_LEARN_CHANGE_APP CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_LEARN_CHANGE_APP
(
  ID             NUMBER(12)                     NOT NULL,
  USER_ID        VARCHAR2(100 BYTE)             NOT NULL,
  LEARN_APP_ID   NUMBER(12)                     NOT NULL,
  CARDINAL_ID    NUMBER(12)		                NOT NULL,
  OLD_COURSE_ID  VARCHAR2(12 BYTE)              NOT NULL,
  NEW_COURSE_ID  VARCHAR2(12 BYTE)              NOT NULL,
  STATE          CHAR(1 BYTE)                   DEFAULT '1',
  USE_YN         CHAR(1 BYTE)                   DEFAULT 'Y',
  REG_USER       VARCHAR2(100 BYTE)             DEFAULT NULL,
  REG_DATE       VARCHAR2(14 BYTE)              DEFAULT NULL,
  UPD_USER       VARCHAR2(100 BYTE)             DEFAULT NULL,
  UPD_DATE       VARCHAR2(14 BYTE)              DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_LEARN_CHANGE_APP IS '연수 변경신청 관리 테이블';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.ID IS '변경신청 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.USER_ID IS '변경신청자 아이디';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.LEARN_APP_ID IS '수강신청 마스터 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.CARDINAL_ID IS '기수 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.OLD_COURSE_ID IS '기존 과정 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.NEW_COURSE_ID IS '변경신청 과정 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.STATE IS '변경신청 상태(1:신청(접수 처리중), 2:변경완료, 3:변경불가)';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_CHANGE_APP.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010423.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_LEARN_CHANGE_APP ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_LEARN_CHANGE_APP;
  
  CREATE SEQUENCE SEQ_LEARN_CHANGE_APP INCREMENT BY 1 START WITH 1;