ALTER TABLE BOGUN.T_LEARN_APP
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_LEARN_APP CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_LEARN_APP
(
  ID            NUMBER(12)                      NOT NULL,
  USER_ID       VARCHAR2(100 BYTE)              NOT NULL,
  COURSE_ID     VARCHAR2(12 BYTE)               NOT NULL,
  CARDINAL_ID	NUMBER(12)                      NOT NULL,
  ONOFF_TYPE    VARCHAR2(1 BYTE)                NOT NULL,
  MEM_GBN       VARCHAR2(1 BYTE)                NOT NULL,
  MEM_SUB_GBN   VARCHAR2(2 BYTE)                DEFAULT NULL,
  TEL           VARCHAR2(50 BYTE)               DEFAULT NULL,
  PHONE         VARCHAR2(50 BYTE)               DEFAULT NULL,
  EMAIL         VARCHAR2(100 BYTE)              DEFAULT NULL,
  APP_STATE     CHAR(1 BYTE)                    DEFAULT NULL,
  LEARN_START_DATE		VARCHAR2(10 BYTE)       DEFAULT NULL,
  LEARN_END_DATE        VARCHAR2(10 BYTE)       DEFAULT NULL,
  REQ_TYPE      CHAR(1 BYTE)                    DEFAULT NULL,
  REQ_MEMO      VARCHAR2(255 BYTE)              DEFAULT NULL,
  REQ_DATE      VARCHAR2(10 BYTE)               DEFAULT NULL,
  TOTAL_SCORE   NUMBER(3)                       DEFAULT '0',
  ISSUE_NUM     VARCHAR2(50 BYTE)               DEFAULT NULL,
  USE_YN        CHAR(1 BYTE)                    DEFAULT 'Y',
  REG_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  REG_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL,
  UPD_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  UPD_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_LEARN_APP IS '수강신청 관리 테이블';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.ID IS '수강신청 마스터 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.USER_ID IS '수강신청 유저';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.COURSE_ID IS '과정 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.CARDINAL_ID IS '과정 기수 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.ONOFF_TYPE IS '온오프라인교육타입';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.MEM_GBN IS '신청회원구분(회원테이블참조)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.MEM_SUB_GBN IS '신청회원하위구분(회원테이블참조)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.TEL IS '연락처';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.PHONE IS '핸드폰';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.EMAIL IS '이메일';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.APP_STATE IS '신청상태(1:접수, 2:대상선정탈락, 3:대상자지정완료)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.LEARN_START_DATE IS '연수시작일';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.LEARN_END_DATE IS '연수종료일';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.REQ_TYPE IS '신청변경요청구분(1:연기요청, 2:취소요청, 3:수강연기, 4:수강취소)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.REQ_MEMO IS '변경요청사유';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.REQ_DATE IS '변경요청일자(연기 및 취소 요청일자)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.TOTAL_SCORE IS '최종성적(진도율+온라인평가+온라인과제+출석평가(4학점이상)을 집계';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.ISSUE_NUM IS '이수번호(이수시 이수번호 발급)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010686.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_LEARN_APP ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_LEARN_APP;
  
  CREATE SEQUENCE SEQ_LEARN_APP INCREMENT BY 1 START WITH 1;