ALTER TABLE BOGUN.T_LEARN_APP_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_LEARN_APP_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_LEARN_APP_DETAIL
(
  LEARN_APP_ID           NUMBER(12)             NOT NULL,
  EDU_YN                 VARCHAR2(1 BYTE)       DEFAULT 'N',
  EDU_YEAR               VARCHAR2(4 BYTE)       DEFAULT NULL,
  EDU_COURSE             VARCHAR2(100 BYTE)     DEFAULT NULL,
  PARENTS_YN             VARCHAR2(1 BYTE)       DEFAULT 'N',
  CHILDS                 VARCHAR2(100 BYTE)     DEFAULT NULL,
  ORG_NAME               VARCHAR2(255 BYTE)     DEFAULT NULL,
  ORG_REGION_CODE        VARCHAR2(12 BYTE)      DEFAULT NULL,
  ORG_TEL                VARCHAR2(50 BYTE)      DEFAULT NULL,
  ORG_FAX                VARCHAR2(50 BYTE)      DEFAULT NULL,
  ORG_POST_CODE          VARCHAR2(8 BYTE)       DEFAULT NULL,
  ORG_ADDR1              VARCHAR2(200 BYTE)     DEFAULT NULL,
  ORG_ADDR2              VARCHAR2(200 BYTE)     DEFAULT NULL,
  ORG_PERSON_TOT         NUMBER(5)              DEFAULT 0,
  ORG_PERSON_CUR         NUMBER(5)              DEFAULT 0,
  MNGR_NAME              VARCHAR2(255 BYTE)     DEFAULT NULL,
  MNGR_POSITION          VARCHAR2(20 BYTE)      DEFAULT NULL,
  MNGR_TEL               VARCHAR2(50 BYTE)      DEFAULT NULL,
  MNGR_PHONE             VARCHAR2(50 BYTE)      DEFAULT NULL,
  MNGR_FAX               VARCHAR2(50 BYTE)      DEFAULT NULL,
  MNGR_EMAIL             VARCHAR2(100 BYTE)     DEFAULT NULL,
  ORG_EDU_YN             VARCHAR2(1 BYTE)       DEFAULT 'N',
  ORG_EDU_YEAR           VARCHAR2(4 BYTE)       DEFAULT NULL,
  OFF_ORG_PERSON_CNT     NUMBER(5)              DEFAULT 0,
  OFF_PARENTS_CNT        NUMBER(5)              DEFAULT 0,
  OFF_EDU_LOCATION_TYPE  VARCHAR2(1 BYTE)       DEFAULT NULL,
  OFF_EDU_LOCATION       VARCHAR2(100 BYTE)     DEFAULT NULL,
  OFF_EQUIP_PC_YN        CHAR(1 BYTE)           DEFAULT 'N',
  OFF_EQUIP_TV_YN        CHAR(1 BYTE)           DEFAULT 'N',
  OFF_EQUIP_PRJT_YN      CHAR(1 BYTE)           DEFAULT 'N',
  USE_YN                 CHAR(1 BYTE)           DEFAULT 'Y',
  REG_USER               VARCHAR2(100 BYTE)     DEFAULT NULL,
  REG_DATE        		 VARCHAR2(14 BYTE)      DEFAULT NULL,
  UPD_USER               VARCHAR2(100 BYTE)     DEFAULT NULL,
  UPD_DATE        		 VARCHAR2(14 BYTE)      DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_LEARN_APP_DETAIL IS '수강신청 상세 테이블';

COMMENT ON COLUMN BOGUN.T_LEARN_APP_DETAIL.LEARN_APP_ID IS '수강신청 마스터 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP_DETAIL.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_LEARN_APP_DETAIL.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP_DETAIL.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_LEARN_APP_DETAIL.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_APP_DETAIL.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010656.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_LEARN_APP_DETAIL ADD (
  PRIMARY KEY
  (LEARN_APP_ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);