ALTER TABLE BOGUN.T_LEARN_DELAY_APP
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_LEARN_DELAY_APP CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_LEARN_DELAY_APP
(
  ID            NUMBER(12)                      NOT NULL,
  USER_ID       VARCHAR2(100 BYTE)              NOT NULL,
  LEARN_APP_ID  NUMBER(12)                      NOT NULL,
  TEL           VARCHAR2(50 BYTE)               DEFAULT NULL,
  PHONE         VARCHAR2(50 BYTE)               DEFAULT NULL,
  EMAIL         VARCHAR2(100 BYTE)              DEFAULT NULL,
  MEMO          VARCHAR2(1000 BYTE)             DEFAULT NULL,
  STATE         CHAR(1 BYTE)                    DEFAULT '1',
  USE_YN        CHAR(1 BYTE)                    DEFAULT 'Y',
  REG_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  REG_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL,
  UPD_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  UPD_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_LEARN_DELAY_APP IS '연수 연기신청 관리 테이블';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.ID IS '연기신청 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.USER_ID IS '신청자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.LEARN_APP_ID IS '수강신청 마스터 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.TEL IS '연락처';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.PHONE IS '핸드폰';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.EMAIL IS '전자우편';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.MEMO IS '연기신청 요청사유';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.STATE IS '연기신청상태(1:신청(접수 처리중), 2:연기완료, 3:연기불가)';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_LEARN_DELAY_APP.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010427.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_LEARN_DELAY_APP ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_LEARN_DELAY_APP;
  
  CREATE SEQUENCE SEQ_LEARN_DELAY_APP INCREMENT BY 1 START WITH 1;