ALTER TABLE BOGUN.T_MANAGER
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_MANAGER CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_MANAGER
(
  ID            VARCHAR2(100 BYTE)              NOT NULL,
  PW            VARCHAR2(100 BYTE)              NOT NULL,
  NAME          VARCHAR2(50 BYTE)               DEFAULT NULL,
  LOCALE        CHAR(2 BYTE)                    DEFAULT 'ko',
  COURSE_CODE   CHAR(12 BYTE)                   DEFAULT NULL,
  SNS_CD        CHAR(2 BYTE)                    DEFAULT NULL,
  SNS_ID        VARCHAR2(50 BYTE)               DEFAULT NULL,
  SNS_URL       VARCHAR2(255 BYTE)              DEFAULT NULL,
  ACCEPT_SNS    CHAR(1 BYTE)                    DEFAULT 'Y',
  ACCEPT_EMAIL  CHAR(1 BYTE)                    DEFAULT 'N',
  ACCEPT_SMS    CHAR(1 BYTE)                    DEFAULT 'N',
  TEL           VARCHAR2(50 BYTE)               DEFAULT NULL,
  PHONE         VARCHAR2(50 BYTE)               DEFAULT NULL,
  FAX           VARCHAR2(50 BYTE)               DEFAULT NULL,
  EMAIL         VARCHAR2(100 BYTE)              DEFAULT NULL,
  EMAIL_YN      CHAR(1 BYTE)                    DEFAULT 'N',
  GENDER        CHAR(1 BYTE)                    DEFAULT 'M',
  BIRTH_DAY     VARCHAR2(10 BYTE)               DEFAULT NULL,
  POST_CODE     VARCHAR2(8 BYTE)                DEFAULT NULL,
  ADDR1         VARCHAR2(200 BYTE)              DEFAULT NULL,
  ADDR2         VARCHAR2(200 BYTE)              DEFAULT NULL,
  LAST_LOGIN    VARCHAR2(14 BYTE)               DEFAULT NULL,
  AUTH_KEY      VARCHAR2(20 BYTE)               DEFAULT NULL,
  SESSION_ID    VARCHAR2(100 BYTE)              DEFAULT NULL,
  GRADE         NUMBER(3)                       DEFAULT '1',
  DEPT_CODE     VARCHAR2(20 BYTE)               DEFAULT NULL,
  BELONG_TO     VARCHAR2(500 BYTE)              DEFAULT NULL,
  PHOTO_FILE    VARCHAR2(20 BYTE)               DEFAULT NULL,
  PROFILE       VARCHAR2(4000 BYTE),
  ORDER_NUM     NUMBER(3)                       DEFAULT '1',
  USE_YN        CHAR(1 BYTE)                    DEFAULT 'Y',
  REG_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL,
  UPD_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_MANAGER IS 'MANAGER MASTER TABLE';

COMMENT ON COLUMN BOGUN.T_MANAGER.ID IS 'MANAGER ID';

COMMENT ON COLUMN BOGUN.T_MANAGER.PW IS 'MANAGER 계정 비밀번호';

COMMENT ON COLUMN BOGUN.T_MANAGER.NAME IS 'MANAGER명';

COMMENT ON COLUMN BOGUN.T_MANAGER.LOCALE IS '사용자 언어 (ko/en/zh/ja)';

COMMENT ON COLUMN BOGUN.T_MANAGER.COURSE_CODE IS '강사대표과정분류';

COMMENT ON COLUMN BOGUN.T_MANAGER.SNS_CD IS 'SNS 서비스: 페이스북 FB/ 인스타그램 IG/ 카카오스토리 KS/ 트위터 TW/ 구글플러스 GP/ 네이버 NV';

COMMENT ON COLUMN BOGUN.T_MANAGER.SNS_ID IS 'SNS 사용자 ID';

COMMENT ON COLUMN BOGUN.T_MANAGER.SNS_URL IS 'SNS 프로파일 URL';

COMMENT ON COLUMN BOGUN.T_MANAGER.ACCEPT_SNS IS 'SNS 연결 여부 (Y/N)';

COMMENT ON COLUMN BOGUN.T_MANAGER.ACCEPT_EMAIL IS 'EMAIL 수신 여부 (Y/N)';

COMMENT ON COLUMN BOGUN.T_MANAGER.ACCEPT_SMS IS 'SMS 수신 여부 (Y/N)';

COMMENT ON COLUMN BOGUN.T_MANAGER.TEL IS '연락처';

COMMENT ON COLUMN BOGUN.T_MANAGER.PHONE IS '핸드폰';

COMMENT ON COLUMN BOGUN.T_MANAGER.FAX IS '팩스';

COMMENT ON COLUMN BOGUN.T_MANAGER.EMAIL IS '이메일';

COMMENT ON COLUMN BOGUN.T_MANAGER.EMAIL_YN IS '이메일 인증 여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_MANAGER.GENDER IS '성별: 남자(M), 여자(F)';

COMMENT ON COLUMN BOGUN.T_MANAGER.BIRTH_DAY IS '생년월일: 1999-01-01';

COMMENT ON COLUMN BOGUN.T_MANAGER.POST_CODE IS '우편번호(신:5자리, 구:6자리)';

COMMENT ON COLUMN BOGUN.T_MANAGER.ADDR1 IS '주소1: 우편번호에 연결된 주소';

COMMENT ON COLUMN BOGUN.T_MANAGER.ADDR2 IS '주소2: 상세주소 (사용자 입력)';

COMMENT ON COLUMN BOGUN.T_MANAGER.LAST_LOGIN IS '마지막 접속일';

COMMENT ON COLUMN BOGUN.T_MANAGER.AUTH_KEY IS '랜덤 인증번호';

COMMENT ON COLUMN BOGUN.T_MANAGER.SESSION_ID IS '생셩 된 세션 ID';

COMMENT ON COLUMN BOGUN.T_MANAGER.GRADE IS 'MANAGER 등급멤버 등급(1~9)';

COMMENT ON COLUMN BOGUN.T_MANAGER.DEPT_CODE IS '부서코드';

COMMENT ON COLUMN BOGUN.T_MANAGER.BELONG_TO IS '소속명칭';

COMMENT ON COLUMN BOGUN.T_MANAGER.PHOTO_FILE IS '사진첨부';

COMMENT ON COLUMN BOGUN.T_MANAGER.PROFILE IS '약력';

COMMENT ON COLUMN BOGUN.T_MANAGER.ORDER_NUM IS '순서(필요없음)';

COMMENT ON COLUMN BOGUN.T_MANAGER.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_MANAGER.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_MANAGER.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010521.
--  The object is created when the parent object is created.

--  There is no statement for index BOGUN.SYS_C0010522.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_MANAGER ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);