ALTER TABLE BOGUN.T_MEMBER_ORG_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_MEMBER_ORG_INFO CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_MEMBER_ORG_INFO
(
  USER_ID     	   VARCHAR2(100 BYTE)              NOT NULL,
  ORG_NAME         VARCHAR2(255 BYTE)           DEFAULT NULL,
  ORG_REGION_CODE  VARCHAR2(12 BYTE)            DEFAULT NULL,
  ORG_TEL          VARCHAR2(50 BYTE)            DEFAULT NULL,
  ORG_FAX          VARCHAR2(50 BYTE)            DEFAULT NULL,
  ORG_POST_CODE    VARCHAR2(8 BYTE)             DEFAULT NULL,
  ORG_ADDR1        VARCHAR2(200 BYTE)           DEFAULT NULL,
  ORG_ADDR2        VARCHAR2(200 BYTE)           DEFAULT NULL,
  ORG_PERSON_TOT   NUMBER(5)                    DEFAULT 0,
  ORG_PERSON_CUR   NUMBER(5)                    DEFAULT 0,
  MNGR_NAME        VARCHAR2(255 BYTE)           DEFAULT NULL,
  MNGR_TEL         VARCHAR2(50 BYTE)            DEFAULT NULL,
  MNGR_PHONE       VARCHAR2(50 BYTE)            DEFAULT NULL,
  MNGR_FAX         VARCHAR2(50 BYTE)            DEFAULT NULL,
  MNGR_EMAIL       VARCHAR2(100 BYTE)           DEFAULT NULL,
  ORG_EDU_YN       VARCHAR2(1 BYTE)             DEFAULT 'N',
  ORG_EDU_YEAR     VARCHAR2(4 BYTE)             DEFAULT NULL,
  EQUIP_PC_YN      CHAR(1 BYTE)                 DEFAULT 'N',
  EQUIP_TV_YN      CHAR(1 BYTE)                 DEFAULT 'N',
  EQUIP_PRJT_YN    CHAR(1 BYTE)                 DEFAULT 'N'
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_MEMBER_ORG_INFO IS '회원기관정보';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.USER_ID IS '회원ID';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_NAME IS '기관명';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_REGION_CODE IS '기관지역코드';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_TEL IS '기관 대표전화';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_FAX IS '기관 FAX번호';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_POST_CODE IS '기관 우편주소';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_ADDR1 IS '기관 주소';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_ADDR2 IS '기관 상세주소';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_PERSON_TOT IS '기관 정원';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_PERSON_CUR IS '기관 현원';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.MNGR_NAME IS '담당자명';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.MNGR_TEL IS '담당자 전화번호';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.MNGR_PHONE IS '담당자 휴대폰번호';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.MNGR_FAX IS '담당자 FAX번호';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.MNGR_EMAIL IS '담당자 EMAIL';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_EDU_YN IS '이전교육여부';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.ORG_EDU_YEAR IS '최근교육년도';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.EQUIP_PC_YN IS 'PC존재여부';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.EQUIP_TV_YN IS 'TV존재여부';

COMMENT ON COLUMN BOGUN.T_MEMBER_ORG_INFO.EQUIP_PRJT_YN IS '프로젝터존재여부';


--  There is no statement for index BOGUN.SYS_C0010658.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_MEMBER_ORG_INFO ADD (
  PRIMARY KEY
  (USER_ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);