ALTER TABLE BOGUN.T_MEMBER_OUT
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_MEMBER_OUT CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_MEMBER_OUT
(
  ID        NUMBER(12)                          NOT NULL,
  USER_ID   VARCHAR2(100 BYTE)                  NOT NULL,
  NOTE      VARCHAR2(500 BYTE)                  DEFAULT NULL,
  USE_YN    CHAR(1 BYTE)                        DEFAULT 'Y',
  REG_DATE  VARCHAR2(14 BYTE)                   DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_MEMBER_OUT IS '탈퇴회원 관리 TABLE';

COMMENT ON COLUMN BOGUN.T_MEMBER_OUT.ID IS 'MEMBER 탈퇴 ID';

COMMENT ON COLUMN BOGUN.T_MEMBER_OUT.USER_ID IS 'MEMBER ID';

COMMENT ON COLUMN BOGUN.T_MEMBER_OUT.NOTE IS '사유/비고';

COMMENT ON COLUMN BOGUN.T_MEMBER_OUT.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_MEMBER_OUT.REG_DATE IS '등록일자';


--  There is no statement for index BOGUN.SYS_C0010438.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_MEMBER_OUT ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_MEMBER_OUT;
  
  CREATE SEQUENCE SEQ_MEMBER_OUT INCREMENT BY 1 START WITH 1;