ALTER TABLE BOGUN.T_NOTE
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_NOTE CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_NOTE
(
  ID                NUMBER(12)                  NOT NULL,
  FROM_USER_ID      VARCHAR2(100 BYTE)          NOT NULL,
  TO_USER_ID        VARCHAR2(100 BYTE)          NOT NULL,
  TITLE             VARCHAR2(100 BYTE)          NOT NULL,
  NOTE              VARCHAR2(4000 BYTE),
  SAVE_YN           CHAR(1 BYTE)                DEFAULT 'Y',
  PROC_YN           CHAR(1 BYTE)                DEFAULT 'N',
  FROM_USER_USE_YN  CHAR(1 BYTE)                DEFAULT 'Y'                   NOT NULL,
  TO_USER_USE_YN    CHAR(1 BYTE)                DEFAULT 'Y'                   NOT NULL,
  SEND_DATE         VARCHAR2(14 BYTE)           DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_NOTE IS '쪽지함 관리 테이블';

COMMENT ON COLUMN BOGUN.T_NOTE.ID IS '쪽지 ID';

COMMENT ON COLUMN BOGUN.T_NOTE.FROM_USER_ID IS '보낸사람(admin 인 경우 관리자)';

COMMENT ON COLUMN BOGUN.T_NOTE.TO_USER_ID IS '받은사람(admin 인 경우 관리자)';

COMMENT ON COLUMN BOGUN.T_NOTE.TITLE IS '제목';

COMMENT ON COLUMN BOGUN.T_NOTE.NOTE IS '쪽지내용';

COMMENT ON COLUMN BOGUN.T_NOTE.SAVE_YN IS '보낸쪽지함에 저장??';

COMMENT ON COLUMN BOGUN.T_NOTE.PROC_YN IS '처리상태(Y:읽음,N:안읽음)';

COMMENT ON COLUMN BOGUN.T_NOTE.FROM_USER_USE_YN IS '발송인쪽지사용여부(삭제여부)';

COMMENT ON COLUMN BOGUN.T_NOTE.TO_USER_USE_YN IS '수신인쪽지사용여부(삭제여부)';

COMMENT ON COLUMN BOGUN.T_NOTE.SEND_DATE IS '발신일시';


--  There is no statement for index BOGUN.SYS_C0010445.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_NOTE ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_NOTE;
  
  CREATE SEQUENCE SEQ_NOTE INCREMENT BY 1 START WITH 1;