ALTER TABLE BOGUN.T_QUIZ_POOL
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_QUIZ_POOL CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_QUIZ_POOL
(
  ID         NUMBER(12)                         NOT NULL,
  COURSE_ID  VARCHAR2(12 BYTE)                  NOT NULL,
  TITLE      VARCHAR2(100 BYTE)                 NOT NULL,
  QUIZ_TYPE  CHAR(1 BYTE)                       DEFAULT '2',
  ORDER_NUM  NUMBER(3)                          DEFAULT '1',
  USE_YN     CHAR(1 BYTE)                       DEFAULT 'Y',
  REG_USER   VARCHAR2(100 BYTE)                 DEFAULT NULL,
  REG_DATE   VARCHAR2(14 BYTE)                  DEFAULT NULL,
  UPD_USER   VARCHAR2(100 BYTE)                 DEFAULT NULL,
  UPD_DATE   VARCHAR2(14 BYTE)                  DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_QUIZ_POOL IS '시험지 풀 관리(과정별로 관리) 테이블';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.ID IS '시험지 POOL ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.COURSE_ID IS '과정 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.TITLE IS '시험지 풀 명';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.QUIZ_TYPE IS '시험 종류(1:출석고사, 2:온라인평가, 3:온라인과제)';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.ORDER_NUM IS '순서(필요없음)';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.USE_YN IS '시험상태(Y : 사용, N : 사용안함)';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_POOL.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010465.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_QUIZ_POOL ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_QUIZ_POOL;
  
  CREATE SEQUENCE SEQ_QUIZ_POOL INCREMENT BY 1 START WITH 1;