ALTER TABLE BOGUN.T_QUIZ_BANK
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_QUIZ_BANK CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_QUIZ_BANK
(
  ID          NUMBER(12)                        NOT NULL,
  COURSE_ID   VARCHAR2(12 BYTE)                 NOT NULL,
  QUIZ_TYPE   CHAR(1 BYTE)                      DEFAULT '2',
  CLASS_TYPE  CHAR(1 BYTE)                      DEFAULT NULL,
  TITLE       VARCHAR2(2000 BYTE)               NOT NULL,
  OS_TYPE     CHAR(1 BYTE)                      DEFAULT 'O',
  EXAM_TYPE   CHAR(1 BYTE)                      DEFAULT '1',
  EXAM1       VARCHAR2(2000 BYTE)               DEFAULT NULL,
  EXAM2       VARCHAR2(2000 BYTE)               DEFAULT NULL,
  EXAM3       VARCHAR2(2000 BYTE)               DEFAULT NULL,
  EXAM4       VARCHAR2(2000 BYTE)               DEFAULT NULL,
  EXAM5       VARCHAR2(2000 BYTE)               DEFAULT NULL,
  CATEGORY    VARCHAR2(10 BYTE)                 DEFAULT NULL,
  CATE_NAME   VARCHAR2(50 BYTE)                 DEFAULT NULL,
  CMNT        VARCHAR2(4000 BYTE),
  QUIZ_LEVEL  NUMBER(3)                         DEFAULT '1',
  O_ANSWER    NUMBER(3)                         DEFAULT '1',
  S_ANSWER    VARCHAR2(4000 BYTE),
  ORDER_NUM   NUMBER(3)                         DEFAULT '1',
  USE_YN      CHAR(1 BYTE)                      DEFAULT 'Y',
  REG_USER    VARCHAR2(100 BYTE)                DEFAULT NULL,
  REG_DATE    VARCHAR2(14 BYTE)                 DEFAULT NULL,
  UPD_USER    VARCHAR2(100 BYTE)                DEFAULT NULL,
  UPD_DATE    VARCHAR2(14 BYTE)                 DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_QUIZ_BANK IS '시험 문제 뱅크 관리 테이블';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.ID IS '문제 뱅크 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.COURSE_ID IS '과정 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.QUIZ_TYPE IS '시험 종류(1:출석고사, 2:온라인평가, 3:온라인과제)';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.CLASS_TYPE IS '문제유형(A:A형, B:B형, C:C형)';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.TITLE IS '문제명';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.OS_TYPE IS '문항종류(O:객관식, S:주관식)';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.EXAM_TYPE IS '객관식 유형(1:4지선다, 2:5지선다)';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.EXAM1 IS '객관식 1번 보기';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.EXAM2 IS '객관식 2번 보기';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.EXAM3 IS '객관식 3번 보기';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.EXAM4 IS '객관식 4번 보기';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.EXAM5 IS '객관식 5번 보기';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.CATEGORY IS '문항척도분류코드';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.CATE_NAME IS '문항척도분류명';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.CMNT IS '보충해설';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.QUIZ_LEVEL IS '퀴즈 난이도(1:하, 2:중, 3:상)';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.O_ANSWER IS '객관식 정답';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.S_ANSWER IS '주관식 정답';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.ORDER_NUM IS '순서';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_BANK.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010457.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_QUIZ_BANK ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_QUIZ_BANK;
  
  CREATE SEQUENCE SEQ_QUIZ_BANK INCREMENT BY 1 START WITH 1;