ALTER TABLE BOGUN.T_QUIZ_ITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_QUIZ_ITEM CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_QUIZ_ITEM
(
  ID            NUMBER(12)                      NOT NULL,
  QUIZ_POOL_ID  NUMBER(12)                      NOT NULL,
  QUIZ_BANK_ID  NUMBER(12)                      NOT NULL,
  ORDER_NUM     NUMBER(3)                       DEFAULT '1',
  USE_YN        CHAR(1 BYTE)                    DEFAULT 'Y',
  REG_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  REG_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL,
  UPD_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  UPD_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_QUIZ_ITEM IS '시험지 문제 관리 테이블';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.ID IS '시험지 문항 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.QUIZ_POOL_ID IS '시험지 풀 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.QUIZ_BANK_ID IS '문제 은행 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.ORDER_NUM IS '문제순서';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_QUIZ_ITEM.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010461.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_QUIZ_ITEM ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_QUIZ_ITEM;
  
  CREATE SEQUENCE SEQ_QUIZ_ITEM INCREMENT BY 1 START WITH 1;