ALTER TABLE BOGUN.T_REPORT
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_REPORT CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_REPORT
(
  ID            NUMBER(12)                      NOT NULL,
  LEARN_APP_ID  NUMBER(12)                      NOT NULL,
  CARDINAL_ID   NUMBER(12) 		                NOT NULL,
  COURSE_ID     VARCHAR2(12 BYTE)               NOT NULL,
  QUIZ_ID       VARCHAR2(20 BYTE)               NOT NULL,
  USER_ID       VARCHAR2(20 BYTE)               NOT NULL,
  QUIZ_TYPE     CHAR(1 BYTE)                    DEFAULT '2',
  EXAM_SPOT_ID  VARCHAR2(3 BYTE)                DEFAULT NULL,
  EXAM_NUM      VARCHAR2(8 BYTE)                DEFAULT NULL,
  ANSWER        VARCHAR2(200 BYTE)              DEFAULT NULL,
  SCORE         NUMBER(3)                       DEFAULT '0',
  FILE_ID       VARCHAR2(20 BYTE)               DEFAULT NULL,
  USER_FILE_ID  VARCHAR2(20 BYTE)               DEFAULT NULL,
  MARK_YN       CHAR(1 BYTE)                    DEFAULT 'N',
  ORDER_NUM     NUMBER(3)                       DEFAULT '1',
  USE_YN        CHAR(1 BYTE)                    DEFAULT 'Y',
  REG_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  REG_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL,
  UPD_USER      VARCHAR2(100 BYTE)              DEFAULT NULL,
  UPD_DATE      VARCHAR2(14 BYTE)               DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_REPORT IS '시험 문제 성적 평가 테이블';

COMMENT ON COLUMN BOGUN.T_REPORT.ID IS '성적 평가 ID';

COMMENT ON COLUMN BOGUN.T_REPORT.LEARN_APP_ID IS '수강신청ID';

COMMENT ON COLUMN BOGUN.T_REPORT.CARDINAL_ID IS '기수 ID';

COMMENT ON COLUMN BOGUN.T_REPORT.COURSE_ID IS '과정 ID';

COMMENT ON COLUMN BOGUN.T_REPORT.QUIZ_ID IS '시험 ID';

COMMENT ON COLUMN BOGUN.T_REPORT.USER_ID IS '평가대상 ID';

COMMENT ON COLUMN BOGUN.T_REPORT.QUIZ_TYPE IS '시험 종류(1:출석고사, 2:온라인평가, 3:온라인과제)';

COMMENT ON COLUMN BOGUN.T_REPORT.EXAM_SPOT_ID IS '출석평가 시 고사장ID(3자리로 고정)';

COMMENT ON COLUMN BOGUN.T_REPORT.EXAM_NUM IS '출석평가 수험번호(고사장코드(3)+교시(1)+일련번호(4) : 총 8자리)';

COMMENT ON COLUMN BOGUN.T_REPORT.ANSWER IS '출석평가문제답안(답안OX : OOOXOOOOXOXXXXOOOOOOXXXOXOO 또는 1O2X3O4O5X6X7X8O)';

COMMENT ON COLUMN BOGUN.T_REPORT.SCORE IS '시험 종류별 점수';

COMMENT ON COLUMN BOGUN.T_REPORT.FILE_ID IS '문제 답안 파일ID(과제의 정답을 파일로 제출한 경우 저장)';

COMMENT ON COLUMN BOGUN.T_REPORT.USER_FILE_ID IS '출석고사 증명사진';

COMMENT ON COLUMN BOGUN.T_REPORT.MARK_YN IS '채점여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_REPORT.ORDER_NUM IS '순서';

COMMENT ON COLUMN BOGUN.T_REPORT.USE_YN IS '사용여부(Y : 사용, N : 미사용)';

COMMENT ON COLUMN BOGUN.T_REPORT.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_REPORT.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_REPORT.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_REPORT.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010477.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_REPORT ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_REPORT;
  
  CREATE SEQUENCE SEQ_REPORT INCREMENT BY 1 START WITH 1;