ALTER TABLE BOGUN.T_SURVEY_REPLY
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_SURVEY_REPLY CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_SURVEY_REPLY
(
  ID         NUMBER(12)                         NOT NULL,
  SURVEY_ID  VARCHAR2(14 BYTE)                  NOT NULL,
  ITEM_ID    NUMBER(12)                         NOT NULL,
  ITEM_TYPE  CHAR(1 BYTE)                       DEFAULT '1',
  EXAM1_YN   CHAR(1 BYTE)                       DEFAULT 'N',
  EXAM2_YN   CHAR(1 BYTE)                       DEFAULT 'N',
  EXAM3_YN   CHAR(1 BYTE)                       DEFAULT 'N',
  EXAM4_YN   CHAR(1 BYTE)                       DEFAULT 'N',
  EXAM5_YN   CHAR(1 BYTE)                       DEFAULT 'N',
  EXAM6_YN   CHAR(1 BYTE)                       DEFAULT 'N',
  EXAM7_YN   CHAR(1 BYTE)                       DEFAULT 'N',
  EXAM1      VARCHAR2(500 BYTE)                 DEFAULT NULL,
  EXAM2      VARCHAR2(500 BYTE)                 DEFAULT NULL,
  EXAM3      VARCHAR2(500 BYTE)                 DEFAULT NULL,
  EXAM4      VARCHAR2(500 BYTE)                 DEFAULT NULL,
  EXAM5      VARCHAR2(500 BYTE)                 DEFAULT NULL,
  EXAM6      VARCHAR2(500 BYTE)                 DEFAULT NULL,
  EXAM7      VARCHAR2(500 BYTE)                 DEFAULT NULL,
  ANSWER     VARCHAR2(500 BYTE)                 DEFAULT NULL,
  ORDER_NUM  NUMBER(3)                          DEFAULT '1',
  USE_YN     CHAR(1 BYTE)                       DEFAULT 'Y',
  REG_USER   VARCHAR2(100 BYTE)                 DEFAULT NULL,
  REG_DATE   VARCHAR2(14 BYTE)                  DEFAULT NULL,
  UPD_USER   VARCHAR2(100 BYTE)                 DEFAULT NULL,
  UPD_DATE   VARCHAR2(14 BYTE)                  DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_SURVEY_REPLY IS '설문 문항 답변 TABLE';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.ID IS '문항 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.SURVEY_ID IS '설문 마스터 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.ITEM_ID IS '설문 문항 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.ITEM_TYPE IS '문항유형(1:객관식, 2:주관식, 3:객관+주관식)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM1_YN IS '객관식 또는 객관+주관식 일때 1번 선택여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM2_YN IS '객관식 또는 객관+주관식 일때 2번 선택여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM3_YN IS '객관식 또는 객관+주관식 일때 3번 선택여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM4_YN IS '객관식 또는 객관+주관식 일때 4번 선택여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM5_YN IS '객관식 또는 객관+주관식 일때 5번 선택여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM6_YN IS '객관식 또는 객관+주관식 일때 6번 선택여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM7_YN IS '객관식 또는 객관+주관식 일때 7번 선택여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM1 IS '객관+주관식 1번 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM2 IS '객관+주관식 2번 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM3 IS '객관+주관식 3번 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM4 IS '객관+주관식 4번 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM5 IS '객관+주관식 5번 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM6 IS '객관+주관식 6번 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.EXAM7 IS '객관+주관식 7번 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.ANSWER IS '주관식인 경우 답변';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.ORDER_NUM IS '문항번호';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.USE_YN IS '사용여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_REPLY.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010496.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_SURVEY_REPLY ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_SURVEY_REPLY;
  
  CREATE SEQUENCE SEQ_SURVEY_REPLY INCREMENT BY 1 START WITH 1;