ALTER TABLE BOGUN.T_SURVEY_ITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE BOGUN.T_SURVEY_ITEM CASCADE CONSTRAINTS;

CREATE TABLE BOGUN.T_SURVEY_ITEM
(
  ID           NUMBER(12)                       NOT NULL,
  SURVEY_ID    VARCHAR2(14 BYTE)                NOT NULL,
  ITEM_TYPE    CHAR(1 BYTE)                     DEFAULT '1',
  SURVEY_CODE  VARCHAR2(12 BYTE)                DEFAULT NULL,
  TITLE        VARCHAR2(500 BYTE)               DEFAULT NULL,
  EXAM1        VARCHAR2(200 BYTE)               DEFAULT NULL,
  EXAM2        VARCHAR2(200 BYTE)               DEFAULT NULL,
  EXAM3        VARCHAR2(200 BYTE)               DEFAULT NULL,
  EXAM4        VARCHAR2(200 BYTE)               DEFAULT NULL,
  EXAM5        VARCHAR2(200 BYTE)               DEFAULT NULL,
  EXAM6        VARCHAR2(200 BYTE)               DEFAULT NULL,
  EXAM7        VARCHAR2(200 BYTE)               DEFAULT NULL,
  EXAM1_YN     CHAR(1 BYTE)                     DEFAULT 'N',
  EXAM2_YN     CHAR(1 BYTE)                     DEFAULT 'N',
  EXAM3_YN     CHAR(1 BYTE)                     DEFAULT 'N',
  EXAM4_YN     CHAR(1 BYTE)                     DEFAULT 'N',
  EXAM5_YN     CHAR(1 BYTE)                     DEFAULT 'N',
  EXAM6_YN     CHAR(1 BYTE)                     DEFAULT 'N',
  EXAM7_YN     CHAR(1 BYTE)                     DEFAULT 'N',
  ORDER_NUM    NUMBER(3)                        DEFAULT '1',
  USE_YN       CHAR(1 BYTE)                     DEFAULT 'Y',
  REG_USER     VARCHAR2(100 BYTE)               DEFAULT NULL,
  REG_DATE     VARCHAR2(14 BYTE)                DEFAULT NULL,
  UPD_USER     VARCHAR2(100 BYTE)               DEFAULT NULL,
  UPD_DATE     VARCHAR2(14 BYTE)                DEFAULT NULL
)
TABLESPACE BOGUN
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE BOGUN.T_SURVEY_ITEM IS '설문 문항 TABLE';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.ID IS '설문 문항 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.SURVEY_ID IS '설문 마스터 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.ITEM_TYPE IS '문항유형(1:객관식, 2:주관식, 3:객관+주관식)';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.SURVEY_CODE IS '문항분류코드(기초관리>설문분류)';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.TITLE IS '설문문항질문명';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM1 IS '객관식 1번 보기';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM2 IS '객관식 2번 보기';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM3 IS '객관식 3번 보기';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM4 IS '객관식 4번 보기';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM5 IS '객관식 5번 보기';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM6 IS '객관식 6번 보기';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM7 IS '객관식 7번 보기';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM1_YN IS '객관식 1번 주관식 처리';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM2_YN IS '객관식 2번 주관식 처리';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM3_YN IS '객관식 3번 주관식 처리';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM4_YN IS '객관식 4번 주관식 처리';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM5_YN IS '객관식 5번 주관식 처리';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM6_YN IS '객관식 6번 주관식 처리';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.EXAM7_YN IS '객관식 7번 주관식 처리';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.ORDER_NUM IS '문항번호';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.USE_YN IS '사용여부(Y/N)';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.REG_USER IS '등록자 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.REG_DATE IS '등록일자';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.UPD_USER IS '수정자 ID';

COMMENT ON COLUMN BOGUN.T_SURVEY_ITEM.UPD_DATE IS '수정일자';


--  There is no statement for index BOGUN.SYS_C0010492.
--  The object is created when the parent object is created.

ALTER TABLE BOGUN.T_SURVEY_ITEM ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE BOGUN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
  DROP SEQUENCE SEQ_SURVEY_ITEM;
  
  CREATE SEQUENCE SEQ_SURVEY_ITEM INCREMENT BY 1 START WITH 1;