CREATE TABLE FF_ATTACH_FILE_DETAIL (
	SEQ					INT(12)			AUTO_INCREMENT	UNIQUE		COMMENT '파일 상세 SEQ',
	FILE_ID				VARCHAR(20)									COMMENT '파일 ID',
	FILE_NAME			VARCHAR(100)								COMMENT '파일명',
	ORIGIN_FILE_NAME	VARCHAR(255)								COMMENT '원본 파일명',
	FILE_PATH			VARCHAR(255)	NOT NULL					COMMENT '파일 경로',
	FILE_EXT			VARCHAR(20)		NOT NULL					COMMENT '파일 확장자',
	FILE_SIZE			INT(12)			DEFAULT 0					COMMENT '파일 사이즈',
	URL_PATH			VARCHAR(255)								COMMENT '파일 URL 호출 경로',
	ORDER_NUM			INT(3)			DEFAULT 1					COMMENT '파일 DISPLAY순서(같은 파일 ID별 순서)',
	PRIMARY KEY(FILE_ID, FILE_NAME)
) COMMENT='ATTACHFILE DETAIL TABLE';