CREATE TABLE IDS (
	TABLE_NAME			VARCHAR(20)		PRIMARY KEY					COMMENT 'SEQ를 관리할 테이블명',
	NEXT_ID				INT(12)			NOT NULL					COMMENT 'SEQ',
	REG_DATE			VARCHAR(14)									COMMENT '등록일자',
	UPD_DATE		  	VARCHAR(14)									COMMENT '수정일자'
) COMMENT='ID MANAGER TABLE';