-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE FF_LOGIN_HISTORY (
	ID					INT(12)			AUTO_INCREMENT	PRIMARY KEY	COMMENT '로그인 이력 ID',
	MEMBER_ID			VARCHAR(100)	NOT NULL					COMMENT 'MEMBER ID',
	IP_ADDRESS			VARCHAR(100)								COMMENT '접속 IP ADDRESS',
	LOGIN_DATE			VARCHAR(14)									COMMENT '로그인일시'
) COMMENT='로그인 이력 관리 테이블';