-- DATETIME에 DEFAULT CURRENT_TIMESTAMP 는 mysql 5.6버전 이상부터 가능
-- AUTO_INCREMENT 와 DEFAULT 는 5버전 이상부터는 같이 사용 불가
CREATE TABLE FF_MEMBER (
	SEQ					INT(12)			AUTO_INCREMENT	UNIQUE		COMMENT 'MEMBER 마스터 SEQ',
	ID					VARCHAR(100)	PRIMARY KEY					COMMENT 'MEMBER ID',
	PW					VARCHAR(100)	NOT NULL					COMMENT 'MEMBER 계정 비밀번호',
	NAME				VARCHAR(50)									COMMENT 'MEMBER명',
	LOCALE				CHAR(2)			DEFAULT 'ko' 				COMMENT '사용자 언어 (ko/en/zh/ja)',
	COURSE_CODE			CHAR(12)									COMMENT '대표과정분류',
	SNS_CD				CHAR(2) 									COMMENT 'SNS 서비스: 페이스북 FB/ 인스타그램 IG/ 카카오스토리 KS/ 트위터 TW/ 구글플러스 GP/ 네이버 NV',
  	SNS_ID				VARCHAR(50) 								COMMENT 'SNS 사용자 ID',
  	SNS_URL				VARCHAR(255) 								COMMENT 'SNS 프로파일 URL',
  	ACCEPT_SNS			CHAR(1) 		DEFAULT 'Y' 				COMMENT 'SNS 연결 여부 (Y/N)',
  	ACCEPT_EMAIL		CHAR(1)			DEFAULT 'N' 				COMMENT 'EMAIL 수신 여부 (Y/N)',
  	ACCEPT_SMS			CHAR(1)			DEFAULT 'N' 				COMMENT 'SMS 수신 여부 (Y/N)',
  	TEL					VARCHAR(50)									COMMENT '연락처',
	PHONE				VARCHAR(50)									COMMENT '핸드폰',
	FAX					VARCHAR(50)									COMMENT '팩스',
	EMAIL				VARCHAR(100)								COMMENT '이메일',
	EMAIL_YN			CHAR(1) 		DEFAULT 'N'					COMMENT '이메일 인증 여부(Y/N)',
	GENDER 				CHAR(1) 		DEFAULT 'M' 				COMMENT '성별: 남자(M), 여자(F)',
  	BIRTH_DAY 			VARCHAR(10) 								COMMENT '생년월일: 1999-01-01',
  	POST_CODE 			VARCHAR(8) 									COMMENT '우편번호(신:5자리, 구:6자리)',
  	ADDR1 				VARCHAR(200)								COMMENT '주소1: 우편번호에 연결된 주소',
  	ADDR2 				VARCHAR(200) 								COMMENT '주소2: 상세주소 (사용자 입력)',
	LAST_LOGIN			VARCHAR(14)									COMMENT '마지막 접속일',
	AUTH_KEY			VARCHAR(20)									COMMENT '랜덤 인증번호',
	SESSION_ID			VARCHAR(100)								COMMENT '생셩 된 세션 ID',
	GRADE				INT(1)			DEFAULT 1					COMMENT 'MEMBER 등급멤버 등급(1~9)',
	DEPT_CODE			VARCHAR(20)									COMMENT '부서코드',
	BELONG_TO			VARCHAR(500)								COMMENT '소속명칭',
	PHOTO_FILE			VARCHAR(20)									COMMENT	'사진첨부',
	PROFILE				TEXT										COMMENT '약력',
	IP_ADDRESS			VARCHAR(100)								COMMENT '접속 IP 주소',
	ORDER_NUM			INT(3)			DEFAULT 1					COMMENT '순서(필요없음)',
	USE_YN				CHAR(1)			DEFAULT 'Y'					COMMENT '사용여부(Y : 사용, N : 미사용)',
	REG_DATE			VARCHAR(14)									COMMENT '등록일자',
	UPD_DATE		  	VARCHAR(14)									COMMENT '수정일자'
) COMMENT='MEMBER MASTER TABLE';