CREATE TABLE FF_MEMBER_GROUP (
	MEM_ID			VARCHAR(100)					COMMENT 'MEMBER ID',
	MEM_CODE		VARCHAR(12)						COMMENT 'MEMBER CODE ID',
	PRIMARY KEY(MEM_ID, MEM_CODE)
) COMMENT='MEMBER GROUP CODE MAPPING TABLE';